import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "HerbAlly - Your Trusted Guide to Medicinal Herbs",
    short_name: "HerbAlly",
    description:
      "Explore 2,700+ medicinal herbs, calculate dosages, and check drug interactions.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#16a34a",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // SVG fallback for browsers that prefer vector (e.g. older Safari).
    // The 192/512/maskable PNGs above are generated by
    // scripts/generate-pwa-icons.js from /public/icon.svg.
  };
}
