/**
 * fetch-pubmed-citations.ts
 *
 * Fetches real PubMed citations for herbs that have generic/placeholder citations.
 * Skips herbs that already have real PMID citations.
 *
 * Usage:
 *   npx tsx scripts/fetch-pubmed-citations.ts
 */

import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
import * as fs from "fs";

config({ path: ".env.local" });
config({ path: ".env" });

const MAX_PER_HERB = 2;
const DELAY_MS = 350; // ~3 requests/sec to stay under PubMed rate limit

interface HerbRow {
  id: string;
  name: string;
  slug: string;
  scientific_name: string;
  citations: unknown;
}

interface PubMedResult {
  pmid: string;
  title: string;
  year: number;
}

function hasRealCitations(citations: unknown): boolean {
  if (!citations) return false;
  if (!Array.isArray(citations)) return false;
  if (citations.length === 0) return false;
  // Check if any citation has a PMID (real citation) vs generic placeholders
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return citations.some((c: any) => c.pmid && /^\d{7,8}$/.test(String(c.pmid)));
}

async function searchPubMed(term: string): Promise<PubMedResult[]> {
  const baseUrl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils";

  try {
    // Search for PMIDs
    const searchUrl = `${baseUrl}/esearch.fcgi?db=pubmed&retmax=${MAX_PER_HERB}&retmode=json&sort=relevance&term=${encodeURIComponent(term)}`;
    const searchRes = await fetch(searchUrl);
    if (!searchRes.ok) return [];

    const searchData = (await searchRes.json()) as {
      esearchresult?: { idlist?: string[] };
    };
    const pmids = searchData.esearchresult?.idlist ?? [];
    if (pmids.length === 0) return [];

    // Fetch citation details in XML
    const fetchUrl = `${baseUrl}/efetch.fcgi?db=pubmed&id=${pmids.join(",")}&retmode=xml&rettype=abstract`;
    const fetchRes = await fetch(fetchUrl);
    if (!fetchRes.ok) return [];

    const xml = await fetchRes.text();
    const results: PubMedResult[] = [];

    for (const pmid of pmids) {
      // Extract title using regex that spans multiple lines
      const titleMatch = xml.match(
        new RegExp(
          `<PMID[^>]*>${pmid}</PMID>[\\s\\S]*?<ArticleTitle>([\\s\\S]*?)</ArticleTitle>`
        )
      );
      let title = titleMatch
        ? titleMatch[1].replace(/\s+/g, " ").trim()
        : `Study ${pmid}`;
      // Truncate long titles
      if (title.length > 250) title = title.substring(0, 247) + "...";

      // Extract year
      const yearMatch = xml.match(
        new RegExp(
          `<PMID[^>]*>${pmid}</PMID>[\\s\\S]*?<PubDate>[\\s\\S]*?<Year>(\\d{4})</Year>`
        )
      );
      const year = yearMatch
        ? parseInt(yearMatch[1])
        : new Date().getFullYear();

      results.push({ pmid, title, year });
    }

    return results;
  } catch {
    return [];
  }
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!url || !key) {
    console.error("Missing Supabase credentials");
    process.exit(1);
  }

  const supabase = createClient(url, key);

  // Get all herbs with pagination
  console.log("Fetching herbs from database...");
  const herbList: HerbRow[] = [];
  let page = 0;
  const pageSize = 1000;

  while (true) {
    const { data: herbs, error } = await supabase
      .from("herbs")
      .select("id, name, slug, scientific_name, citations")
      .eq("is_published", true)
      .order("name")
      .range(page * pageSize, (page + 1) * pageSize - 1);

    if (error) {
      console.error("Error:", error);
      process.exit(1);
    }
    if (!herbs || herbs.length === 0) break;

    herbList.push(...(herbs as HerbRow[]));
    page++;
    if (herbs.length < pageSize) break;
  }

  console.log(`Found ${herbList.length} herbs`);

  // Filter to herbs needing real citations
  const needsCitations = herbList.filter((h) => !hasRealCitations(h.citations));
  console.log(
    `${needsCitations.length} herbs need real PubMed citations (${herbList.length - needsCitations.length} already have them)`
  );

  if (needsCitations.length === 0) {
    console.log("All herbs already have real citations!");
    process.exit(0);
  }

  // Open output file
  const outputPath = "supabase/migrations/00032_add_all_pubmed_citations.sql";
  const output = fs.createWriteStream(outputPath);

  output.write(`-- ============================================================================
-- MIGRATION 00032: Real PubMed citations for herbs with placeholder citations
-- ============================================================================
-- Auto-generated by scripts/fetch-pubmed-citations.ts
-- Replaces generic NCCIH/WHO placeholder citations with real PubMed PMIDs.
-- Searches PubMed by scientific name, takes top 1-2 most relevant results.
-- Uses NCBI E-utilities API.
-- Generated: ${new Date().toISOString()}
-- ============================================================================

`);

  let processed = 0;
  let found = 0;
  let empty = 0;
  const startTime = Date.now();

  for (let i = 0; i < needsCitations.length; i++) {
    const herb = needsCitations[i];

    // Search by scientific name
    const results = await searchPubMed(herb.scientific_name);

    if (results.length > 0) {
      const citations = results.map((r) => ({
        source: "PubMed",
        title: r.title,
        url: `https://pubmed.ncbi.nlm.nih.gov/${r.pmid}/`,
        year: r.year,
        pmid: r.pmid,
      }));

      // Escape for SQL
      const escaped = JSON.stringify(citations).replace(/'/g, "''");

      output.write(`-- ${herb.name} (${herb.scientific_name})\n`);
      output.write(
        `UPDATE public.herbs SET citations = '${escaped}'::jsonb WHERE slug = '${herb.slug}';\n\n`
      );
      found++;
    } else {
      empty++;
    }

    processed++;

    // Progress every 50 herbs
    if (processed % 50 === 0) {
      const elapsed = (Date.now() - startTime) / 1000;
      const rate = processed / elapsed;
      const remaining = (needsCitations.length - processed) / rate;
      console.log(
        `  ${processed}/${needsCitations.length} | ${found} found, ${empty} empty | ${rate.toFixed(1)}/sec | ~${Math.ceil(remaining)}s remaining`
      );
    }

    // Rate limiting
    if (i < needsCitations.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, DELAY_MS));
    }
  }

  output.end();

  const elapsed = (Date.now() - startTime) / 1000;
  console.log(`\nDone in ${Math.ceil(elapsed)}s!`);
  console.log(`  Total processed: ${processed}`);
  console.log(`  Citations found: ${found}`);
  console.log(`  No results: ${empty}`);
  console.log(`  Output: ${outputPath}`);
}

main().catch(console.error);
