-- ============================================================================
-- MIGRATION 00029: Add 62 missing key medicinal herbs to production DB
-- ============================================================================
-- These herbs are from the original seed file (00015) but were never applied
-- to the production database. The production DB was populated by AI bulk
-- generation which used botanical Latin names, missing these common-name herbs.
--
-- Each INSERT uses ON CONFLICT (slug) DO NOTHING so it's safe to re-run.
-- ============================================================================

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Turmeric',
  'turmeric',
  'Curcuma longa',
  ARRAY['Indian Saffron', 'Haldi', 'Golden Spice', 'Curcuma'],
  'Turmeric is a bright yellow spice derived from the rhizome of Curcuma longa, a member of the ginger family. It has been used for thousands of years in Ayurvedic and Traditional Chinese Medicine for its potent anti-inflammatory and antioxidant properties. Curcumin, its primary active compound, is one of the most extensively studied natural compounds in modern research.',
  ARRAY['Curcumin', 'Demethoxycurcumin', 'Bisdemethoxycurcumin', 'Turmerone', 'Atlantone'],
  ARRAY['Anti-inflammatory remedy', 'Digestive aid', 'Wound healing', 'Liver tonic', 'Skin conditions'],
  ARRAY['Joint pain and arthritis', 'Inflammatory bowel conditions', 'Antioxidant supplementation', 'Cognitive support', 'Metabolic syndrome support'],
  '500-2000mg standardized extract daily, or 1-3g powder daily',
  'Not generally recommended for children under 12; consult pediatrician',
  ARRAY['capsule','tablet','powder','tea','extract']::public.dosage_form[],
  'Best absorbed with black pepper (piperine) and healthy fats. Can be taken as golden milk by mixing with warm milk and black pepper. Standardized extracts should contain at least 95% curcuminoids.',
  ARRAY['Gallstones or bile duct obstruction', 'Bleeding disorders', 'Pre-surgery (stop 2 weeks before)', 'Iron deficiency (may reduce absorption)'],
  ARRAY['GI upset at high doses', 'Nausea', 'Diarrhea', 'Yellow stool', 'Contact dermatitis in sensitive individuals'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'anti-inflammatory'),
  true
),
(
  gen_random_uuid(),
  'Echinacea',
  'echinacea',
  'Echinacea purpurea',
  ARRAY['Purple Coneflower', 'Coneflower', 'American Coneflower', 'Echinacea angustifolia'],
  'Echinacea is a genus of flowering plants in the daisy family, native to North America. It was traditionally used by Native American tribes for a wide range of conditions including infections and snake bites. Today it is one of the most popular herbal supplements worldwide, primarily used for immune system support.',
  ARRAY['Alkamides', 'Caffeic acid derivatives', 'Chicoric acid', 'Polysaccharides', 'Glycoproteins'],
  ARRAY['Immune stimulant', 'Wound healing', 'Snake bite treatment', 'Toothache remedy', 'Cold and flu treatment'],
  ARRAY['Common cold prevention and treatment', 'Upper respiratory infections', 'Immune system modulation', 'Wound healing support', 'Urinary tract infections'],
  '300-500mg standardized extract 3 times daily, or 2.5ml tincture 3 times daily',
  'Not recommended for children under 12 without medical supervision',
  ARRAY['capsule','tincture','tea','tablet','extract']::public.dosage_form[],
  'Most effective when started at the first sign of cold symptoms. Cycle use (8 weeks on, 1 week off) may be more effective than continuous use. Look for products standardized to echinacosides or chicoric acid.',
  ARRAY['Autoimmune disorders', 'HIV/AIDS', 'Tuberculosis', 'Multiple sclerosis', 'Allergy to daisy family plants'],
  ARRAY['Nausea', 'Stomach pain', 'Allergic reactions', 'Rash', 'Dizziness'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'immune-support'),
  true
),
(
  gen_random_uuid(),
  'Ginkgo Biloba',
  'ginkgo-biloba',
  'Ginkgo biloba',
  ARRAY['Maidenhair Tree', 'Fossil Tree', 'Bai Guo', 'Silver Apricot'],
  'Ginkgo biloba is one of the oldest living tree species, often referred to as a living fossil. Its leaves have been used in Traditional Chinese Medicine for thousands of years. It is one of the top-selling herbal supplements worldwide, primarily used for cognitive function and circulatory health.',
  ARRAY['Ginkgolides', 'Bilobalide', 'Quercetin', 'Kaempferol', 'Isorhamnetin'],
  ARRAY['Memory enhancement', 'Respiratory ailments', 'Circulatory support', 'Tinnitus treatment', 'Longevity tonic'],
  ARRAY['Cognitive decline and dementia', 'Peripheral arterial disease', 'Tinnitus', 'Macular degeneration', 'Vertigo'],
  '120-240mg standardized extract daily in 2-3 divided doses',
  'Not recommended for children under 12',
  ARRAY['capsule','tablet','extract','tincture']::public.dosage_form[],
  'Use standardized extract containing 24% flavone glycosides and 6% terpene lactones. Effects on cognition may take 4-6 weeks. Should be discontinued 2 weeks before surgery.',
  ARRAY['Bleeding disorders', 'Pre-surgery (stop 2 weeks before)', 'Seizure disorders', 'Diabetes (monitor blood sugar)'],
  ARRAY['Headache', 'Dizziness', 'GI upset', 'Allergic skin reactions', 'Increased bleeding risk'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nootropic'),
  true
),
(
  gen_random_uuid(),
  'Garlic',
  'garlic',
  'Allium sativum',
  ARRAY['Stinking Rose', 'Allium', 'Lasun', 'Da Suan'],
  'Garlic is one of the oldest cultivated plants, used for both culinary and medicinal purposes for over 5,000 years. It has been extensively studied for its cardiovascular benefits, antimicrobial properties, and immune-boosting effects. Louis Pasteur first documented its antibacterial properties in 1858.',
  ARRAY['Allicin', 'Ajoene', 'S-allylcysteine', 'Diallyl disulfide', 'Alliin'],
  ARRAY['Infection treatment', 'Cardiovascular tonic', 'Digestive aid', 'Antiparasitic', 'Immune booster'],
  ARRAY['Hypertension support', 'Cholesterol reduction', 'Atherosclerosis prevention', 'Antimicrobial agent', 'Immune system support'],
  '600-1200mg aged garlic extract daily, or 2-5g fresh garlic (1-2 cloves) daily',
  'Small amounts in food are safe; supplements not recommended under 12',
  ARRAY['capsule','tablet','powder','extract','other']::public.dosage_form[],
  'Crushing or chopping fresh garlic activates allicin. Let crushed garlic sit for 10 minutes before cooking to maximize allicin formation. Aged garlic extract is odorless and well-standardized.',
  ARRAY['Bleeding disorders', 'Pre-surgery (stop 1-2 weeks before)', 'GI conditions like GERD'],
  ARRAY['Bad breath', 'Body odor', 'Heartburn', 'GI upset', 'Allergic reactions in sensitive individuals'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'cardiovascular'),
  true
),
(
  gen_random_uuid(),
  'Valerian',
  'valerian',
  'Valeriana officinalis',
  ARRAY['Garden Valerian', 'All-Heal', 'Setwall', 'Garden Heliotrope'],
  'Valerian is a perennial flowering plant native to Europe and Asia, long valued for its sedative and anxiolytic properties. It has been used since ancient Greek and Roman times for insomnia and nervousness. The root is the primary medicinal part, known for its distinctive strong odor.',
  ARRAY['Valerenic acid', 'Isovaleric acid', 'Valepotriates', 'GABA', 'Hesperidin'],
  ARRAY['Insomnia remedy', 'Anxiety relief', 'Nervous tension', 'Digestive spasm relief', 'Headache treatment'],
  ARRAY['Insomnia and sleep disorders', 'Anxiety', 'Restlessness', 'Menstrual cramps', 'Muscle tension'],
  '300-600mg root extract 30-60 minutes before bedtime',
  'Not recommended for children under 3; ages 3-12 use lower doses with supervision',
  ARRAY['capsule','tincture','tea','tablet','extract']::public.dosage_form[],
  'For insomnia, take 30-60 minutes before bedtime. May take 2-4 weeks of regular use for full effect. Valerian tea has a strong taste and odor; capsules may be preferred. Combine with hops or lemon balm for enhanced effect.',
  ARRAY['Liver disease', 'Concurrent sedative medications', 'Before driving or operating machinery'],
  ARRAY['Headache', 'Excitability (paradoxical reaction)', 'Uneasiness', 'Morning grogginess', 'Vivid dreams'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nervine'),
  true
),
(
  gen_random_uuid(),
  'Peppermint',
  'peppermint',
  'Mentha x piperita',
  ARRAY['Mint', 'Brandy Mint', 'Lamb Mint', 'Bo He'],
  'Peppermint is a hybrid mint, a cross between watermint and spearmint, widely used in both traditional and modern medicine. It is particularly valued for its digestive and analgesic properties. Peppermint oil is one of the most well-researched essential oils for irritable bowel syndrome.',
  ARRAY['Menthol', 'Menthone', 'Menthyl acetate', 'Rosmarinic acid', 'Luteolin'],
  ARRAY['Digestive aid', 'Headache relief', 'Cold and flu treatment', 'Nausea remedy', 'Fever reducer'],
  ARRAY['Irritable bowel syndrome', 'Tension headaches', 'Nausea', 'Common cold symptoms', 'Functional dyspepsia'],
  '1-2 enteric-coated capsules (0.2ml oil each) 3 times daily, or 1-3 cups tea daily',
  'Diluted tea safe for children over 2; avoid menthol products near infant faces',
  ARRAY['capsule','tea','essential_oil','tincture','topical']::public.dosage_form[],
  'For IBS, use enteric-coated peppermint oil capsules to prevent heartburn. Tea: steep fresh or dried leaves for 7-10 minutes. Topical: dilute essential oil to 2-3% in carrier oil for headache application on temples.',
  ARRAY['GERD or hiatal hernia', 'Gallbladder disorders', 'Infants and very young children (menthol risk)'],
  ARRAY['Heartburn', 'Nausea at high doses', 'Allergic reactions', 'Perianal burning with enteric-coated capsules', 'Mouth sores from oil'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'digestive'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Aloe Vera',
  'aloe-vera',
  'Aloe barbadensis miller',
  ARRAY['Aloe', 'Burn Plant', 'Lily of the Desert', 'Elephant''s Gall'],
  'Aloe vera is a succulent plant that has been used medicinally for over 6,000 years, dating back to ancient Egypt. The clear gel from its leaves is renowned for wound healing and skin care, while the latex contains potent laxative compounds. It is one of the most widely used plants in the cosmetic and pharmaceutical industries.',
  ARRAY['Acemannan', 'Aloin', 'Barbaloin', 'Anthraquinones', 'Salicylic acid'],
  ARRAY['Burn treatment', 'Wound healing', 'Laxative', 'Skin moisturizer', 'Digestive aid'],
  ARRAY['Burn and wound care', 'Psoriasis', 'Constipation (latex)', 'Oral health', 'Type 2 diabetes support'],
  'Topical gel as needed; internal use 100-200mg aloe latex for constipation; 50ml juice daily',
  'Topical use safe for children; internal use not recommended under 12',
  ARRAY['topical','capsule','extract','other']::public.dosage_form[],
  'For burns and wounds, apply fresh gel directly from the leaf. For internal use, ensure the product is purified and free of aloin if used long-term. Aloe latex (yellow substance under the skin) is a potent laxative and should be used cautiously.',
  ARRAY['Intestinal obstruction', 'Inflammatory bowel disease', 'Kidney disease', 'Heart conditions (internal latex use)'],
  ARRAY['Diarrhea (internal use)', 'Abdominal cramps', 'Electrolyte imbalance (chronic laxative use)', 'Skin irritation in sensitive individuals', 'Allergic contact dermatitis'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'skin-topical'),
  true
),
(
  gen_random_uuid(),
  'Ginseng',
  'ginseng',
  'Panax ginseng',
  ARRAY['Asian Ginseng', 'Korean Ginseng', 'Chinese Ginseng', 'Red Ginseng', 'Ren Shen'],
  'Panax ginseng, also known as Asian or Korean ginseng, is one of the most widely used herbs in Traditional Chinese Medicine. The root has been prized for over 5,000 years as an energy tonic and adaptogen. Its name "Panax" derives from the Greek word for "all-healing," reflecting its traditional reputation as a cure-all.',
  ARRAY['Ginsenosides', 'Panaxans', 'Polysaccharides', 'Peptidoglycans', 'Polyacetylenes'],
  ARRAY['Energy and vitality tonic', 'Longevity herb', 'Immune booster', 'Sexual health enhancer', 'Mental clarity'],
  ARRAY['Physical and mental fatigue', 'Erectile dysfunction', 'Type 2 diabetes management', 'Cognitive performance', 'Immune system support'],
  '200-400mg standardized extract daily, or 0.5-2g dried root daily',
  'Not recommended for children under 12',
  ARRAY['capsule','tablet','powder','tincture','tea']::public.dosage_form[],
  'Red ginseng (steamed) is considered more potent than white ginseng (dried). Cycle use: 2-3 weeks on, 1-2 weeks off. Standardized extracts should contain 4-7% ginsenosides. Best taken in the morning to avoid sleep disturbance.',
  ARRAY['Hypertension', 'Hormone-sensitive cancers', 'Autoimmune conditions', 'Insomnia', 'Bipolar disorder'],
  ARRAY['Insomnia', 'Headache', 'Digestive issues', 'Changes in blood pressure', 'Menstrual irregularities'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Green Tea',
  'green-tea',
  'Camellia sinensis',
  ARRAY['Matcha', 'Sencha', 'Gunpowder Tea', 'Lung Ching', 'Cha'],
  'Green tea is made from the unoxidized leaves of Camellia sinensis and has been consumed in China and Japan for thousands of years. It is one of the most studied beverages for its health benefits, particularly its high concentration of catechins and L-theanine. It provides a unique combination of alertness and calm.',
  ARRAY['Epigallocatechin gallate (EGCG)', 'L-theanine', 'Caffeine', 'Catechins', 'Quercetin'],
  ARRAY['Alertness enhancer', 'Digestive aid', 'Longevity tonic', 'Weight management', 'Antioxidant'],
  ARRAY['Antioxidant protection', 'Cardiovascular health', 'Weight management', 'Cognitive function', 'Cancer risk reduction support'],
  '2-5 cups daily, or 250-500mg standardized extract daily',
  '1-2 cups daily for children over 6; decaffeinated preferred',
  ARRAY['tea','capsule','extract','powder']::public.dosage_form[],
  'Steep green tea at 70-80C for 2-3 minutes to avoid bitterness. Matcha provides the whole leaf in powdered form for maximum benefit. EGCG supplements should be taken with food to reduce liver risk.',
  ARRAY['Caffeine sensitivity', 'Iron deficiency anemia (inhibits iron absorption)', 'Liver disease (high-dose supplements)', 'Anxiety disorders'],
  ARRAY['Caffeine-related effects (insomnia, anxiety)', 'GI upset', 'Liver toxicity at very high doses of extract', 'Headache', 'Iron absorption interference'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'antioxidant'),
  true
),
(
  gen_random_uuid(),
  'Black Cohosh',
  'black-cohosh',
  'Actaea racemosa',
  ARRAY['Bugbane', 'Black Snakeroot', 'Rattleweed', 'Cimicifuga racemosa'],
  'Black cohosh is a perennial plant native to eastern North America, traditionally used by Native Americans for women''s health conditions. It is one of the most researched herbs for menopausal symptoms and has been used in Europe for over 50 years as a menopause treatment. Its mechanism of action remains under investigation.',
  ARRAY['Triterpene glycosides', 'Actein', 'Cimicifugoside', 'Formononetin', 'Fukinolic acid'],
  ARRAY['Menstrual pain relief', 'Menopausal symptom management', 'Rheumatism treatment', 'Labor induction', 'Anti-inflammatory'],
  ARRAY['Menopausal hot flashes', 'Night sweats', 'Menstrual irregularities', 'PMS symptoms', 'Menopausal mood changes'],
  '20-40mg standardized extract (triterpene glycosides) twice daily',
  'Not recommended for children',
  ARRAY['capsule','tablet','tincture','extract']::public.dosage_form[],
  'Use standardized extracts for consistent dosing. Effects may take 4-8 weeks to become apparent. Limit use to 6 months at a time due to limited long-term safety data. Remifemin is a well-studied brand.',
  ARRAY['Liver disease', 'Hormone-sensitive cancers', 'Seizure disorders', 'Aspirin allergy'],
  ARRAY['GI upset', 'Headache', 'Dizziness', 'Weight gain', 'Rare cases of liver toxicity'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'womens-health'),
  true
),
(
  gen_random_uuid(),
  'Saw Palmetto',
  'saw-palmetto',
  'Serenoa repens',
  ARRAY['Sabal', 'American Dwarf Palm', 'Cabbage Palm', 'Serenoa'],
  'Saw palmetto is a small palm native to the southeastern United States, long used by Native Americans for urinary and reproductive issues. It is one of the most commonly used herbal supplements for benign prostatic hyperplasia (BPH) and has been widely studied in Europe for prostate health.',
  ARRAY['Fatty acids', 'Beta-sitosterol', 'Lauric acid', 'Myristic acid', 'Oleic acid'],
  ARRAY['Urinary tract support', 'Prostate health', 'Male vitality', 'Hair loss prevention', 'Anti-inflammatory'],
  ARRAY['Benign prostatic hyperplasia (BPH)', 'Lower urinary tract symptoms', 'Male pattern baldness', 'Prostate inflammation', 'Hormonal balance in men'],
  '160mg standardized extract (85-95% fatty acids) twice daily, or 320mg once daily',
  'Not indicated for children',
  ARRAY['capsule','tablet','extract','tincture']::public.dosage_form[],
  'Liposterolic extracts are the most studied form. Take with food for better absorption. Effects on BPH symptoms may take 4-6 weeks. Does not reduce prostate size like finasteride but improves symptoms.',
  ARRAY['Hormone-sensitive conditions', 'Bleeding disorders', 'Pre-surgery'],
  ARRAY['Mild GI upset', 'Headache', 'Dizziness', 'Nausea', 'Decreased libido (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'mens-health'),
  true
),
(
  gen_random_uuid(),
  'Licorice Root',
  'licorice-root',
  'Glycyrrhiza glabra',
  ARRAY['Licorice', 'Sweet Root', 'Gan Cao', 'Mulethi', 'Liquorice'],
  'Licorice root is one of the most widely used herbs in Traditional Chinese Medicine, appearing in numerous classical formulas. It has been used for over 4,000 years for respiratory, digestive, and adrenal support. Glycyrrhizin, its primary active compound, is 50 times sweeter than sucrose.',
  ARRAY['Glycyrrhizin', 'Glabridin', 'Liquiritigenin', 'Isoliquiritigenin', 'Glycyrrhetinic acid'],
  ARRAY['Sore throat remedy', 'Cough suppressant', 'Digestive aid', 'Adrenal tonic', 'Harmonizing herb in formulas'],
  ARRAY['Peptic ulcer support', 'Adrenal fatigue', 'Sore throat and cough', 'Hepatitis C support', 'Eczema (topical)'],
  '200-600mg standardized extract daily; DGL (deglycyrrhizinated) 380-760mg before meals',
  'Small amounts in herbal teas for children over 4; avoid high-dose supplements',
  ARRAY['capsule','tea','tincture','powder','extract']::public.dosage_form[],
  'DGL (deglycyrrhizinated licorice) removes glycyrrhizin and is safer for long-term use, especially for ulcers. Regular licorice should not be used for more than 4-6 weeks. Chewable DGL tablets work best taken 20 minutes before meals.',
  ARRAY['Hypertension', 'Heart disease', 'Kidney disease', 'Liver cirrhosis', 'Hypokalemia', 'Hormone-sensitive conditions'],
  ARRAY['Elevated blood pressure', 'Potassium depletion', 'Edema', 'Headache', 'Fatigue', 'Hormonal effects'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'respiratory'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Passionflower',
  'passionflower',
  'Passiflora incarnata',
  ARRAY['Maypop', 'Purple Passionflower', 'Wild Passionflower', 'Apricot Vine'],
  'Passionflower is a climbing vine native to the southeastern United States, traditionally used by Native Americans as a calming herb. It is approved by the German Commission E for nervous restlessness and is widely used in European phytomedicine. It is valued for its anxiolytic properties without significant sedation.',
  ARRAY['Chrysin', 'Vitexin', 'Isovitexin', 'Orientin', 'Apigenin', 'GABA-related compounds'],
  ARRAY['Anxiety relief', 'Insomnia treatment', 'Nervous tension', 'Seizure treatment', 'Pain relief'],
  ARRAY['Generalized anxiety disorder', 'Insomnia', 'Nervous restlessness', 'ADHD support', 'Preoperative anxiety'],
  '200-400mg extract daily, or 1-2 cups tea daily, or 1ml tincture 3 times daily',
  'Not recommended for children under 6; ages 6-12 use half adult dose',
  ARRAY['capsule','tea','tincture','tablet','extract']::public.dosage_form[],
  'For insomnia, take 30-60 minutes before bedtime. Tea: steep 1-2 teaspoons of dried herb in hot water for 10 minutes. Combines well with valerian and lemon balm for enhanced calming effect.',
  ARRAY['Concurrent sedative medications', 'Pregnancy', 'Pre-surgery (stop 2 weeks before)'],
  ARRAY['Drowsiness', 'Dizziness', 'Confusion at high doses', 'Nausea', 'Rapid heartbeat (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nervine'),
  true
),
(
  gen_random_uuid(),
  'Rhodiola',
  'rhodiola',
  'Rhodiola rosea',
  ARRAY['Golden Root', 'Arctic Root', 'Rose Root', 'King''s Crown'],
  'Rhodiola rosea grows in cold, mountainous regions of Europe and Asia and has been used in traditional medicine in Russia and Scandinavia for centuries. It is classified as an adaptogen, helping the body resist physical and mental stress. It has gained significant popularity as a natural performance enhancer and mood stabilizer.',
  ARRAY['Rosavins', 'Salidroside', 'Tyrosol', 'Rhodioflavonoside', 'Rosin'],
  ARRAY['Stamina and endurance enhancer', 'Stress resistance', 'Altitude sickness prevention', 'Depression treatment', 'Fatigue remedy'],
  ARRAY['Stress and fatigue', 'Mild to moderate depression', 'Physical performance', 'Cognitive function under stress', 'Burnout prevention'],
  '200-600mg standardized extract daily (3% rosavins, 1% salidroside)',
  'Not recommended for children under 12',
  ARRAY['capsule','tablet','extract','tincture']::public.dosage_form[],
  'Take in the morning or early afternoon to avoid sleep interference. Standardized extracts should contain 3% rosavins and 1% salidroside. Effects are often noticeable within the first week. Cycle: 5 days on, 2 days off.',
  ARRAY['Bipolar disorder', 'Autoimmune conditions', 'Concurrent stimulant medications'],
  ARRAY['Insomnia (if taken late)', 'Irritability', 'Increased blood pressure', 'Dizziness', 'Dry mouth'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Holy Basil',
  'holy-basil',
  'Ocimum tenuiflorum',
  ARRAY['Tulsi', 'Sacred Basil', 'The Queen of Herbs', 'Hot Basil'],
  'Holy basil, or Tulsi, is one of the most sacred plants in India and a cornerstone of Ayurvedic medicine. It is classified as a rasayana (rejuvenating herb) and adaptogen, used to promote longevity and well-being. Three main varieties exist: Rama (green), Krishna (purple), and Vana (wild).',
  ARRAY['Eugenol', 'Rosmarinic acid', 'Ursolic acid', 'Ocimumosides', 'Linalool'],
  ARRAY['Stress relief', 'Respiratory health', 'Digestive aid', 'Fever treatment', 'Spiritual purification'],
  ARRAY['Stress and anxiety management', 'Blood sugar regulation', 'Respiratory infections', 'Inflammatory conditions', 'Immune system support'],
  '300-600mg extract daily, or 2-3 cups fresh leaf tea daily',
  'Safe as tea for children over 2 in moderate amounts',
  ARRAY['capsule','tea','powder','tincture','extract']::public.dosage_form[],
  'Fresh leaves can be chewed or made into tea. For tea, steep 5-6 fresh leaves or 1 teaspoon dried in hot water for 5-10 minutes. Tulsi is often combined with ginger and honey. Available in multiple varieties; all are medicinal.',
  ARRAY['Fertility concerns (may have anti-fertility effects)', 'Pre-surgery (blood thinning)', 'Hypothyroidism'],
  ARRAY['GI upset', 'Nausea', 'Blood thinning effects', 'Possible anti-fertility effects', 'Mild headache'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Dong Quai',
  'dong-quai',
  'Angelica sinensis',
  ARRAY['Female Ginseng', 'Dang Gui', 'Chinese Angelica', 'Tang Kuei'],
  'Dong quai is a plant in the celery family, widely used in Traditional Chinese Medicine for women''s health conditions. Known as the "female ginseng," it is one of the most commonly prescribed Chinese herbs, appearing in many classical formulas. It is a blood tonic used primarily for menstrual and menopausal concerns.',
  ARRAY['Ligustilide', 'Butylidenephthalide', 'Ferulic acid', 'Polysaccharides', 'Coumarins'],
  ARRAY['Menstrual regulation', 'Blood tonic', 'Pain relief', 'Menopausal support', 'Cardiovascular health'],
  ARRAY['Menstrual irregularities', 'Menopausal symptoms', 'Anemia support', 'Menstrual cramps', 'Cardiovascular health'],
  '200-600mg standardized extract daily, or 3-15g dried root in decoction',
  'Not recommended for children',
  ARRAY['capsule','tablet','tincture','tea','powder']::public.dosage_form[],
  'Traditionally used in combination with other herbs in TCM formulas rather than alone. Decoction: simmer 3-15g dried root in water for 20-30 minutes. Avoid during heavy menstrual bleeding.',
  ARRAY['Bleeding disorders', 'Pre-surgery', 'Hormone-sensitive conditions', 'Fibroids', 'Heavy menstrual bleeding'],
  ARRAY['Photosensitivity', 'Bleeding risk increase', 'GI upset', 'Skin rash', 'Fever'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'womens-health'),
  true
),
(
  gen_random_uuid(),
  'Dandelion',
  'dandelion',
  'Taraxacum officinale',
  ARRAY['Lion''s Tooth', 'Wild Endive', 'Piss-a-Bed', 'Pu Gong Ying'],
  'Dandelion is a widely distributed plant considered a weed by many but valued as a potent medicinal herb for centuries. Every part of the plant is edible and medicinal. The leaves are a natural diuretic rich in potassium, while the root supports liver and digestive health.',
  ARRAY['Taraxacin', 'Inulin', 'Sesquiterpene lactones', 'Chicoric acid', 'Luteolin'],
  ARRAY['Liver tonic', 'Diuretic', 'Digestive bitter', 'Kidney support', 'Blood purifier'],
  ARRAY['Liver support and detoxification', 'Mild diuretic (potassium-sparing)', 'Digestive stimulant', 'Prebiotic support (inulin)', 'Bloating and water retention'],
  '2-8g dried root 3 times daily, or 4-10g fresh leaf daily, or 1-2 cups tea daily',
  'Safe as food; supplement doses for ages 6-12 at half adult dose',
  ARRAY['tea','capsule','tincture','powder','extract']::public.dosage_form[],
  'Root: roast dried root for a coffee-like tea, or decoct raw root for 10-15 minutes. Leaf: steep in hot water for 10 minutes for a mild diuretic tea. Young leaves are excellent in salads. Ensure harvesting from pesticide-free areas.',
  ARRAY['Bile duct obstruction', 'Gallstones', 'Allergy to Asteraceae family', 'Active gallbladder inflammation'],
  ARRAY['GI upset', 'Heartburn', 'Allergic reactions', 'Increased urination', 'Contact dermatitis'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'liver-support'),
  true
),
(
  gen_random_uuid(),
  'Red Clover',
  'red-clover',
  'Trifolium pratense',
  ARRAY['Wild Clover', 'Meadow Clover', 'Cow Clover', 'Purple Clover'],
  'Red clover is a wild plant belonging to the legume family, found in meadows throughout Europe and Asia. It is a rich source of isoflavones (phytoestrogens) and has been used traditionally as a blood purifier and for respiratory conditions. Modern research focuses primarily on its use for menopausal symptoms.',
  ARRAY['Biochanin A', 'Formononetin', 'Genistein', 'Daidzein', 'Pratensein'],
  ARRAY['Blood purifier', 'Cough remedy', 'Skin conditions', 'Women''s health', 'Cancer prevention folk remedy'],
  ARRAY['Menopausal hot flashes', 'Osteoporosis prevention', 'Cardiovascular health', 'Skin health', 'High cholesterol support'],
  '40-160mg isoflavones daily, or 2-3 cups flower tea daily',
  'Not recommended for children',
  ARRAY['capsule','tea','tincture','tablet','extract']::public.dosage_form[],
  'For tea, steep 1-3 teaspoons of dried flower heads in hot water for 10-15 minutes. Standardized extracts (such as Promensil) provide consistent isoflavone content. Fresh flowers can be added to salads.',
  ARRAY['Hormone-sensitive cancers (breast, uterine, ovarian)', 'Bleeding disorders', 'Pre-surgery', 'Protein S deficiency'],
  ARRAY['Headache', 'Nausea', 'Rash', 'Muscle aches', 'Vaginal spotting'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'womens-health'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Cranberry',
  'cranberry',
  'Vaccinium macrocarpon',
  ARRAY['American Cranberry', 'Large Cranberry', 'Bearberry'],
  'Cranberry is a North American native fruit widely recognized for its role in urinary tract health. It contains proanthocyanidins (PACs) that prevent bacteria from adhering to urinary tract walls. Cranberry is one of the best-studied botanicals for UTI prevention and is recommended by many healthcare practitioners.',
  ARRAY['Proanthocyanidins (PACs)', 'Quercetin', 'Myricetin', 'Hippuric acid', 'Vitamin C'],
  ARRAY['Urinary tract health', 'Scurvy prevention', 'Wound healing', 'Stomach ailments', 'Liver problems'],
  ARRAY['Urinary tract infection prevention', 'Recurrent UTI management', 'Helicobacter pylori reduction', 'Cardiovascular health', 'Antioxidant supplementation'],
  '500mg cranberry extract 1-2 times daily, or 240-300ml unsweetened juice daily',
  'Unsweetened juice safe for children over 1; capsules for ages 6+',
  ARRAY['capsule','tablet','extract','other']::public.dosage_form[],
  'Look for products standardized to proanthocyanidins (PACs), ideally 36mg PACs daily. Unsweetened cranberry juice is preferred over sweetened varieties. Capsules and tablets provide more concentrated PACs than juice.',
  ARRAY['Kidney stones (oxalate type)', 'Aspirin allergy (contains salicylic acid)'],
  ARRAY['GI upset at high doses', 'Diarrhea', 'Kidney stone risk (high doses)', 'Blood sugar elevation (sweetened products)'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'urinary'),
  true
),
(
  gen_random_uuid(),
  'Oregano',
  'oregano',
  'Origanum vulgare',
  ARRAY['Wild Marjoram', 'Mountain Mint', 'Joy of the Mountain', 'Origanum'],
  'Oregano is a culinary herb native to the Mediterranean region with powerful antimicrobial properties. Oil of oregano contains high concentrations of carvacrol and thymol, which have demonstrated broad-spectrum antibacterial, antifungal, and antiviral activity. It is increasingly used as a natural antibiotic alternative.',
  ARRAY['Carvacrol', 'Thymol', 'Rosmarinic acid', 'Beta-caryophyllene', 'Naringin'],
  ARRAY['Respiratory infections', 'Digestive aid', 'Antimicrobial agent', 'Parasite treatment', 'Pain relief'],
  ARRAY['Bacterial and fungal infections', 'Upper respiratory infections', 'Candida overgrowth', 'Parasitic infections', 'Small intestinal bacterial overgrowth (SIBO)'],
  '200-600mg oil of oregano capsule daily, or 2-3 drops diluted oil 2-3 times daily',
  'Culinary amounts safe; oil of oregano not recommended for children under 6',
  ARRAY['capsule','essential_oil','tea','tincture']::public.dosage_form[],
  'Oil of oregano should be emulsified or in enteric-coated capsules for internal use. Dilute essential oil with carrier oil for topical use (1:3 ratio). For tea, steep 1-2 teaspoons of dried herb for 10 minutes. Use for short periods (2-4 weeks) for antimicrobial purposes.',
  ARRAY['Allergy to Lamiaceae family', 'Iron deficiency (may reduce absorption)', 'Bleeding disorders'],
  ARRAY['GI irritation', 'Heartburn', 'Allergic reactions', 'Mouth/throat irritation from undiluted oil'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'antimicrobial'),
  true
),
(
  gen_random_uuid(),
  'Rosemary',
  'rosemary',
  'Salvia rosmarinus',
  ARRAY['Compass Plant', 'Dew of the Sea', 'Old Man', 'Rosmarin'],
  'Rosemary is an aromatic evergreen herb native to the Mediterranean, used since ancient times for memory enhancement and cognitive function. It has been a symbol of remembrance across cultures and was traditionally burned as incense. Modern research supports its cognitive-enhancing and antioxidant properties.',
  ARRAY['Carnosic acid', 'Rosmarinic acid', '1,8-Cineole', 'Camphor', 'Carnosol'],
  ARRAY['Memory enhancement', 'Digestive stimulant', 'Hair growth promoter', 'Circulatory tonic', 'Preservative'],
  ARRAY['Cognitive function and memory', 'Hair growth and scalp health', 'Antioxidant protection', 'Digestive support', 'Inflammation reduction'],
  '1-2g dried herb as tea 3 times daily, or 200-350mg standardized extract daily',
  'Culinary amounts safe; supplement doses for ages 6-12 at half adult dose',
  ARRAY['tea','capsule','essential_oil','tincture','topical']::public.dosage_form[],
  'For memory and focus, rosemary essential oil aromatherapy is well-studied. For tea, steep fresh or dried leaves for 5-10 minutes. Rosemary oil diluted in carrier oil can be massaged into the scalp for hair health.',
  ARRAY['Seizure disorders', 'Hypertension (large doses)', 'Pregnancy (large therapeutic doses)'],
  ARRAY['GI irritation at high doses', 'Allergic reactions', 'Seizures (very high doses of oil)', 'Contact dermatitis'],
  false,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'nootropic'),
  true
),
(
  gen_random_uuid(),
  'Thyme',
  'thyme',
  'Thymus vulgaris',
  ARRAY['Common Thyme', 'Garden Thyme', 'Red Thyme', 'Mother of Thyme'],
  'Thyme is an aromatic herb from the mint family, native to the Mediterranean, used both culinarily and medicinally for thousands of years. It is particularly valued for respiratory conditions due to its potent antimicrobial and expectorant properties. Thyme extract is an approved treatment for bronchitis in Germany.',
  ARRAY['Thymol', 'Carvacrol', 'Linalool', 'Rosmarinic acid', 'Luteolin'],
  ARRAY['Cough remedy', 'Respiratory infections', 'Digestive aid', 'Antiseptic', 'Wound healing'],
  ARRAY['Bronchitis', 'Cough and sore throat', 'Upper respiratory infections', 'Oral health', 'Antimicrobial applications'],
  '1-2g dried herb as tea 3 times daily, or thyme syrup 10ml 3 times daily',
  'Safe as tea for children over 2; thyme honey for cough in children over 1',
  ARRAY['tea','tincture','essential_oil','capsule','other']::public.dosage_form[],
  'For cough, steep 1-2 teaspoons in hot water for 10 minutes and add honey. Thyme honey is excellent for sore throats. Essential oil should never be taken internally undiluted. Thyme steam inhalation helps with congestion.',
  ARRAY['Allergy to mint family', 'Hormone-sensitive conditions (thymol has weak estrogenic effects)'],
  ARRAY['GI irritation', 'Allergic reactions', 'Headache', 'Dizziness (essential oil)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'respiratory'),
  true
),
(
  gen_random_uuid(),
  'Sage',
  'sage',
  'Salvia officinalis',
  ARRAY['Common Sage', 'Garden Sage', 'True Sage', 'Dalmatian Sage'],
  'Sage has been used medicinally since ancient Roman times and its Latin name Salvia derives from "salvare" meaning "to save." It is particularly valued for cognitive enhancement, menopausal hot flash reduction, and sore throat relief. Modern research has confirmed its cholinesterase-inhibiting properties relevant to memory.',
  ARRAY['Thujone', 'Camphor', 'Rosmarinic acid', 'Carnosic acid', 'Ursolic acid'],
  ARRAY['Memory enhancement', 'Sore throat gargle', 'Excessive sweating treatment', 'Digestive aid', 'Menopausal support'],
  ARRAY['Cognitive function and memory', 'Menopausal hot flashes', 'Sore throat', 'Excessive sweating (hyperhidrosis)', 'Blood sugar regulation'],
  '300-600mg dried leaf or extract daily, or 2-3 cups tea daily',
  'Culinary amounts safe; medicinal doses for ages 6-12 at half adult dose',
  ARRAY['tea','capsule','tincture','essential_oil','extract']::public.dosage_form[],
  'For sore throat, gargle with cooled sage tea. For hot flashes, sage leaf extract capsules are most effective. Do not use sage essential oil internally (thujone toxicity). Fresh sage tea: steep 1-2 teaspoons for 5-10 minutes.',
  ARRAY['Seizure disorders (thujone)', 'Pregnancy', 'Hormone-sensitive conditions'],
  ARRAY['Dry mouth', 'GI upset', 'Dizziness', 'Allergic reactions', 'Seizures (very high thujone doses)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nootropic'),
  true
),
(
  gen_random_uuid(),
  'Fenugreek',
  'fenugreek',
  'Trigonella foenum-graecum',
  ARRAY['Methi', 'Greek Hay', 'Bird''s Foot', 'Goat''s Horn'],
  'Fenugreek is an annual leguminous plant used in traditional medicine across India, the Middle East, and North Africa. Its seeds are particularly valued for blood sugar regulation, digestive support, and lactation promotion. It contains a unique amino acid, 4-hydroxyisoleucine, that has direct insulin-sensitizing effects.',
  ARRAY['4-Hydroxyisoleucine', 'Diosgenin', 'Galactomannan fiber', 'Trigonelline', 'Saponins'],
  ARRAY['Digestive aid', 'Lactation promoter', 'Blood sugar regulator', 'Anti-inflammatory', 'Aphrodisiac'],
  ARRAY['Type 2 diabetes support', 'Lactation enhancement', 'Testosterone support', 'Cholesterol reduction', 'Appetite control'],
  '500-1000mg seed extract daily, or 5-30g seed powder with meals',
  'Not recommended in supplement doses for children under 12',
  ARRAY['capsule','powder','tea','extract','other']::public.dosage_form[],
  'Soak seeds overnight and consume in the morning for blood sugar benefits. For lactation, 500-1000mg capsules 3 times daily. Seeds can be sprouted for enhanced bioavailability. Warning: may cause maple syrup-like body/urine odor.',
  ARRAY['Peanut or chickpea allergy (cross-reactivity)', 'Hormone-sensitive conditions', 'Concurrent diabetes medications'],
  ARRAY['GI upset', 'Diarrhea', 'Maple syrup body odor', 'Bloating', 'Uterine stimulation (high doses)'],
  false,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'metabolic'),
  true
),
(
  gen_random_uuid(),
  'Neem',
  'neem',
  'Azadirachta indica',
  ARRAY['Indian Lilac', 'Margosa', 'Nimba', 'Divine Tree'],
  'Neem is an evergreen tree native to the Indian subcontinent, revered in Ayurvedic medicine as a powerful purifying herb. Every part of the tree has medicinal applications. It has potent antimicrobial, antifungal, and insecticidal properties and is widely used in traditional medicine across South Asia and Africa.',
  ARRAY['Azadirachtin', 'Nimbin', 'Nimbidin', 'Gedunin', 'Quercetin'],
  ARRAY['Blood purifier', 'Skin conditions', 'Dental hygiene', 'Fever treatment', 'Pest control'],
  ARRAY['Skin infections and conditions', 'Dental health', 'Antifungal treatment', 'Blood sugar regulation', 'Head lice treatment'],
  '300-600mg leaf extract daily, or neem oil topically as needed',
  'Topical use in diluted form for children over 2; internal use not recommended for children',
  ARRAY['capsule','powder','topical','extract','other']::public.dosage_form[],
  'For skin conditions, dilute neem oil in carrier oil (10-20% concentration). Neem leaf tea is very bitter; capsules may be preferred. For dental health, neem bark powder can be used as a tooth powder. Do not ingest neem oil.',
  ARRAY['Autoimmune conditions', 'Fertility concerns (anti-fertility effects)', 'Organ transplant recipients', 'Infants (neem oil is toxic to infants)'],
  ARRAY['GI upset', 'Nausea', 'Vomiting (high doses)', 'Fatigue', 'Headache'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'antimicrobial'),
  true
),
(
  gen_random_uuid(),
  'Spirulina',
  'spirulina',
  'Arthrospira platensis',
  ARRAY['Blue-Green Algae', 'Spirulina Algae', 'Tecuitlatl'],
  'Spirulina is a blue-green microalgae that has been consumed as food for centuries by the Aztecs and African populations. It is one of the most nutrient-dense foods on the planet, containing complete protein, iron, B vitamins, and powerful antioxidants. NASA has studied it as a potential food for space missions.',
  ARRAY['Phycocyanin', 'Beta-carotene', 'GLA (gamma-linolenic acid)', 'Chlorophyll', 'SOD (superoxide dismutase)'],
  ARRAY['Nutritional supplement', 'Energy booster', 'Immune support', 'Detoxification', 'Endurance enhancer'],
  ARRAY['Nutritional supplementation', 'Allergic rhinitis', 'Cholesterol reduction', 'Heavy metal detoxification', 'Antioxidant protection'],
  '1-3g daily for general supplementation; up to 10g daily for therapeutic use',
  '1-3g daily for children over 4',
  ARRAY['powder','tablet','capsule']::public.dosage_form[],
  'Start with a small dose (500mg) and increase gradually to assess tolerance. Mix powder into smoothies, juices, or water. Choose products tested for heavy metals and microcystins. Tablets are convenient for those who dislike the taste.',
  ARRAY['Phenylketonuria (contains phenylalanine)', 'Autoimmune conditions', 'Bleeding disorders'],
  ARRAY['GI upset', 'Headache', 'Muscle pain', 'Sweating', 'Insomnia', 'Allergic reactions'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nutritive'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Chlorella',
  'chlorella',
  'Chlorella vulgaris',
  ARRAY['Green Algae', 'Sun Chlorella', 'Freshwater Algae'],
  'Chlorella is a single-celled freshwater green algae that has been used as a nutritional supplement since the 1960s. It is exceptionally rich in chlorophyll and has been studied for its detoxification properties, particularly for heavy metals. Its tough cell wall must be cracked for proper nutrient absorption.',
  ARRAY['Chlorophyll', 'Chlorella Growth Factor (CGF)', 'Beta-glucans', 'Nucleic acids', 'Lutein'],
  ARRAY['Detoxification', 'Nutritional supplement', 'Immune support', 'Energy booster', 'Wound healing'],
  ARRAY['Heavy metal detoxification', 'Immune system support', 'Cholesterol reduction', 'Nutritional supplementation', 'Blood sugar regulation'],
  '2-3g daily for general supplementation; up to 10g daily for detoxification',
  '1-2g daily for children over 4',
  ARRAY['tablet','powder','capsule']::public.dosage_form[],
  'Choose "broken cell wall" chlorella for better digestibility and absorption. Start with a small dose and increase gradually. Can be mixed into smoothies or taken as tablets. May cause green discoloration of stool.',
  ARRAY['Iodine sensitivity', 'Autoimmune conditions', 'Mold allergy'],
  ARRAY['GI upset', 'Nausea', 'Green stool', 'Gas', 'Photosensitivity', 'Allergic reactions'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nutritive'),
  true
),
(
  gen_random_uuid(),
  'Tribulus',
  'tribulus',
  'Tribulus terrestris',
  ARRAY['Puncture Vine', 'Gokshura', 'Caltrop', 'Goat Head'],
  'Tribulus terrestris is a spiny plant found in tropical and warm temperate regions worldwide. It has been used in both Ayurvedic and Traditional Chinese Medicine for urinary and reproductive health. It is popularly marketed for testosterone support and athletic performance, though clinical evidence is mixed.',
  ARRAY['Protodioscin', 'Steroidal saponins', 'Flavonoids', 'Alkaloids', 'Tannins'],
  ARRAY['Urinary tract support', 'Male vitality', 'Kidney stone prevention', 'Cardiac tonic', 'Diuretic'],
  ARRAY['Libido enhancement', 'Urinary tract health', 'Sports performance', 'Kidney stone prevention', 'Blood sugar regulation'],
  '250-750mg standardized extract (45-60% saponins) daily',
  'Not recommended for children',
  ARRAY['capsule','tablet','extract','powder']::public.dosage_form[],
  'Look for extracts standardized to 45-60% saponins or protodioscin. Take with meals. Cycle use: 8 weeks on, 2-4 weeks off. Bulgarian tribulus extracts are traditionally considered highest quality.',
  ARRAY['Hormone-sensitive conditions', 'Prostate conditions', 'Diabetes medications (risk of hypoglycemia)', 'Lithium use'],
  ARRAY['GI upset', 'Insomnia', 'Restlessness', 'Nausea', 'Irregular menstruation'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'mens-health'),
  true
),
(
  gen_random_uuid(),
  'Cordyceps',
  'cordyceps',
  'Cordyceps militaris',
  ARRAY['Caterpillar Fungus', 'Dong Chong Xia Cao', 'Yartsa Gunbu', 'Winter Worm Summer Grass'],
  'Cordyceps is a genus of parasitic fungi that has been used in Traditional Chinese and Tibetan medicine for centuries. Wild Cordyceps sinensis grows on caterpillar larvae in the Himalayas and is extremely expensive. Modern cultivation techniques now produce Cordyceps militaris, which has similar bioactive compounds.',
  ARRAY['Cordycepin', 'Adenosine', 'Polysaccharides', 'Cordycepic acid', 'Beta-glucans'],
  ARRAY['Energy and vitality tonic', 'Kidney support', 'Lung tonic', 'Sexual health', 'Longevity herb'],
  ARRAY['Athletic performance and endurance', 'Energy and fatigue', 'Respiratory health', 'Kidney function support', 'Immune system modulation'],
  '1000-3000mg fruiting body extract daily',
  'Not well studied in children; generally not recommended under 12',
  ARRAY['capsule','powder','tincture','extract']::public.dosage_form[],
  'Cordyceps militaris fruiting body is the most validated and affordable form. CS-4 (mycelium) is also well-studied. Take in the morning or before exercise for energy benefits. Hot water extraction releases polysaccharides; alcohol extraction releases cordycepin.',
  ARRAY['Autoimmune conditions', 'Bleeding disorders', 'Pre-surgery', 'Hormone-sensitive cancers'],
  ARRAY['GI upset', 'Nausea', 'Diarrhea', 'Dry mouth', 'Metallic taste'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Turkey Tail',
  'turkey-tail',
  'Trametes versicolor',
  ARRAY['Yun Zhi', 'Kawaratake', 'Cloud Mushroom', 'Coriolus versicolor'],
  'Turkey tail is one of the most common and well-studied medicinal mushrooms worldwide. Named for its colorful, fan-shaped fruiting bodies that resemble turkey tail feathers, it has been used in Traditional Chinese and Japanese medicine for centuries. Its polysaccharide extracts (PSK and PSP) are approved as cancer adjunct therapy in Japan.',
  ARRAY['Polysaccharide-K (PSK)', 'Polysaccharopeptide (PSP)', 'Beta-glucans', 'Ergosterol', 'Quercetin'],
  ARRAY['Immune tonic', 'Liver support', 'Lung health', 'Energy enhancer', 'Cancer folk remedy'],
  ARRAY['Cancer adjunct therapy (with PSK/PSP)', 'Immune system support', 'Gut microbiome health', 'HPV support', 'Chemotherapy side effect reduction'],
  '1-3g extract daily, or 2-9g dried mushroom in decoction',
  'Not well studied in children; generally not recommended under 12',
  ARRAY['capsule','powder','tea','extract']::public.dosage_form[],
  'Hot water extraction is essential to release beta-glucans. Simmer dried mushroom for 1+ hours for tea. Powdered extract is more convenient. Look for products with verified beta-glucan content (30%+). Often combined with other medicinal mushrooms.',
  ARRAY['Autoimmune conditions', 'Organ transplant recipients'],
  ARRAY['GI upset', 'Darkened stool', 'Darkened nail pigmentation', 'Gas and bloating'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'immune-support'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Kava',
  'kava',
  'Piper methysticum',
  ARRAY['Kava Kava', 'Intoxicating Pepper', 'Awa', 'Sakau'],
  'Kava is a plant native to the Pacific Islands where it has been consumed ceremonially for over 3,000 years. It is widely used for its anxiolytic and relaxant properties, and clinical evidence supports its effectiveness for generalized anxiety. Concerns about liver toxicity led to bans in some countries, though quality-controlled products appear safe.',
  ARRAY['Kavain', 'Dihydrokavain', 'Methysticin', 'Yangonin', 'Desmethoxyyangonin'],
  ARRAY['Ceremonial beverage', 'Anxiety relief', 'Social relaxant', 'Pain relief', 'Sleep aid'],
  ARRAY['Generalized anxiety disorder', 'Stress relief', 'Insomnia', 'Muscle relaxation', 'Social anxiety'],
  '120-250mg kavalactones daily in divided doses',
  'Not recommended for children under 18',
  ARRAY['capsule','tincture','tea','extract','powder']::public.dosage_form[],
  'Use only noble kava varieties (not "tudei" or wild). Water-based extracts are considered safer than acetone/ethanol extracts. Traditional preparation: knead root powder in water and strain. Do not combine with alcohol. Limit use to 3 months without medical supervision.',
  ARRAY['Liver disease', 'Heavy alcohol use', 'Depression (may worsen)', 'Parkinson''s disease', 'Concurrent hepatotoxic medications'],
  ARRAY['Liver damage (rare, linked to poor quality products)', 'Drowsiness', 'GI upset', 'Skin rash (kava dermopathy)', 'Headache', 'Dizziness'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nervine'),
  true
),
(
  gen_random_uuid(),
  'Marshmallow Root',
  'marshmallow-root',
  'Althaea officinalis',
  ARRAY['Marsh Mallow', 'White Mallow', 'Sweet Weed', 'Wymote'],
  'Marshmallow root is a plant native to Europe, Western Asia, and North Africa that has been used medicinally for over 2,000 years. Like slippery elm, it produces a mucilaginous substance that soothes and coats irritated tissues. The original marshmallow confection was made from this plant root.',
  ARRAY['Mucilage polysaccharides', 'Flavonoids', 'Phenolic acids', 'Pectin', 'Asparagine'],
  ARRAY['Cough remedy', 'Sore throat soother', 'Digestive aid', 'Wound healing', 'Urinary tract soother'],
  ARRAY['Dry cough', 'Sore throat', 'GERD', 'Irritated mucous membranes', 'Urinary tract irritation'],
  '2-5g dried root in cold infusion daily, or 500-1000mg capsule 3 times daily',
  'Safe as tea for children over 2 at reduced doses',
  ARRAY['capsule','tea','tincture','powder','extract']::public.dosage_form[],
  'Cold infusion preserves mucilage best: soak 1-2 tablespoons in cold water overnight, strain and drink. Hot water extracts other compounds but may reduce mucilage content. Take 30 minutes before or 2 hours after other medications.',
  ARRAY['May slow absorption of other medications', 'Diabetes (may affect blood sugar)'],
  ARRAY['Allergic reactions (rare)', 'GI discomfort', 'Nausea'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'respiratory'),
  true
),
(
  gen_random_uuid(),
  'Mullein',
  'mullein',
  'Verbascum thapsus',
  ARRAY['Common Mullein', 'Great Mullein', 'Aaron''s Rod', 'Velvet Plant'],
  'Mullein is a tall, woolly-leaved biennial plant found throughout Europe and Asia. It has a long history of use in European herbal medicine for respiratory conditions, particularly for dry coughs and ear infections. The leaves and flowers are the primary medicinal parts, known for their expectorant and demulcent properties.',
  ARRAY['Saponins', 'Mucilage', 'Flavonoids', 'Verbascosaponin', 'Aucubin'],
  ARRAY['Cough remedy', 'Ear infection treatment', 'Respiratory aid', 'Anti-inflammatory', 'Wound healing'],
  ARRAY['Dry cough and bronchitis', 'Ear infections (oil drops)', 'Asthma support', 'Upper respiratory infections', 'Sore throat'],
  '1-2g dried leaf or flower as tea 3-4 times daily, or mullein ear oil 2-3 drops twice daily',
  'Mullein tea safe for children over 2; ear oil safe for ages 1+',
  ARRAY['tea','tincture','capsule','extract','topical']::public.dosage_form[],
  'Strain tea well through fine cloth to remove tiny leaf hairs which can irritate the throat. For ear oil: infuse fresh mullein flowers in olive oil for 2 weeks. Do not use ear oil if eardrum is perforated. Combine with other respiratory herbs like licorice and thyme.',
  ARRAY['Perforated eardrum (for ear oil)'],
  ARRAY['GI upset (rare)', 'Contact dermatitis from leaf hairs', 'Allergic reactions (rare)'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'respiratory'),
  true
),
(
  gen_random_uuid(),
  'Boswellia',
  'boswellia',
  'Boswellia serrata',
  ARRAY['Indian Frankincense', 'Salai Guggul', 'Olibanum', 'Shallaki'],
  'Boswellia is a tree resin (frankincense) that has been used in Ayurvedic medicine for over 3,000 years for inflammatory and arthritic conditions. Its primary active compounds, boswellic acids, are unique 5-lipoxygenase inhibitors. Clinical trials support its use for osteoarthritis, inflammatory bowel disease, and asthma.',
  ARRAY['Acetyl-11-keto-beta-boswellic acid (AKBA)', 'Beta-boswellic acid', 'Incensole', 'Lupeolic acid', 'Tirucallic acid'],
  ARRAY['Joint pain relief', 'Respiratory support', 'Digestive anti-inflammatory', 'Wound healing', 'Anti-inflammatory'],
  ARRAY['Osteoarthritis', 'Rheumatoid arthritis', 'Inflammatory bowel disease', 'Asthma', 'Tendonitis and joint inflammation'],
  '300-500mg standardized extract (30-65% boswellic acids) 2-3 times daily',
  'Not recommended for children without medical supervision',
  ARRAY['capsule','tablet','extract','topical']::public.dosage_form[],
  'Look for extracts standardized to AKBA (acetyl-11-keto-beta-boswellic acid). Take with a fatty meal for better absorption. Some formulations use phospholipid complexes for enhanced bioavailability. Effects may take 4-8 weeks.',
  ARRAY['Concurrent anti-inflammatory medications', 'Pregnancy'],
  ARRAY['GI upset', 'Nausea', 'Diarrhea', 'Acid reflux', 'Allergic reactions (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'anti-inflammatory'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Willow Bark',
  'willow-bark',
  'Salix alba',
  ARRAY['White Willow', 'European Willow', 'Salicin Willow'],
  'Willow bark has been used for pain relief since at least the time of Hippocrates in 400 BC. It contains salicin, which the body converts to salicylic acid, the compound that inspired the development of aspirin. It is considered a gentler alternative to aspirin for chronic pain conditions.',
  ARRAY['Salicin', 'Salicortin', 'Tremulacin', 'Flavonoids', 'Tannins'],
  ARRAY['Pain relief', 'Fever reduction', 'Anti-inflammatory', 'Headache treatment', 'Back pain remedy'],
  ARRAY['Low back pain', 'Osteoarthritis', 'Headaches', 'Inflammatory conditions', 'Fever'],
  '240mg salicin daily (typically 2-3 capsules of standardized extract)',
  'Not recommended for children under 16 (Reye syndrome risk)',
  ARRAY['capsule','tea','tincture','extract','tablet']::public.dosage_form[],
  'For tea, simmer 1-2 teaspoons of bark in water for 15-20 minutes. Standardized extracts provide consistent salicin content. Effects are slower but longer-lasting than aspirin. Do not use as a substitute for aspirin in cardiovascular prevention.',
  ARRAY['Aspirin allergy or sensitivity', 'Bleeding disorders', 'Children under 16', 'Kidney disease', 'Concurrent blood thinners'],
  ARRAY['GI upset', 'Nausea', 'Allergic reactions', 'Kidney irritation', 'Rash'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'analgesic'),
  true
),
(
  gen_random_uuid(),
  'Butterbur',
  'butterbur',
  'Petasites hybridus',
  ARRAY['Blatterdock', 'Bog Rhubarb', 'Pestilence Wort', 'Butter Dock'],
  'Butterbur is a perennial plant native to Europe and parts of Asia, used since ancient times for plague, fever, and respiratory conditions. Modern clinical trials have established it as an effective treatment for migraine prevention and allergic rhinitis. Only PA-free (pyrrolizidine alkaloid-free) products should be used.',
  ARRAY['Petasin', 'Isopetasin', 'Oxopetasin', 'Flavonoids', 'Sesquiterpenes'],
  ARRAY['Plague treatment', 'Fever reduction', 'Headache relief', 'Respiratory support', 'Antispasmodic'],
  ARRAY['Migraine prevention', 'Allergic rhinitis (hay fever)', 'Asthma', 'Headache prevention', 'Urinary spasms'],
  '50-75mg PA-free extract twice daily for migraines',
  'PA-free extracts may be used for children 6-17 at reduced doses under medical supervision',
  ARRAY['capsule','tablet','extract']::public.dosage_form[],
  'CRITICAL: Only use certified PA-free (pyrrolizidine alkaloid-free) products such as Petadolex. Raw or unprocessed butterbur contains toxic PAs that can damage the liver. For migraine prevention, take consistently for at least 4 weeks.',
  ARRAY['Liver disease', 'Allergy to ragweed or daisy family', 'Pregnancy', 'Non-PA-free products (liver toxicity)'],
  ARRAY['GI upset', 'Belching', 'Headache', 'Fatigue', 'Liver damage (from PA-containing products)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'analgesic'),
  true
),
(
  gen_random_uuid(),
  'Yarrow',
  'yarrow',
  'Achillea millefolium',
  ARRAY['Milfoil', 'Soldier''s Woundwort', 'Nosebleed Plant', 'Thousand-Leaf'],
  'Yarrow is a perennial herb found throughout temperate regions worldwide with a rich history of use in wound healing dating back to ancient Greece. Its Latin name refers to the legendary warrior Achilles, who supposedly used it to treat his soldiers'' wounds. It is valued for its hemostatic, anti-inflammatory, and digestive properties.',
  ARRAY['Achillein', 'Azulene', 'Chamazulene', 'Camphor', 'Flavonoids'],
  ARRAY['Wound healing', 'Fever reduction', 'Digestive aid', 'Menstrual regulation', 'Cold remedy'],
  ARRAY['Wound care and hemostasis', 'Digestive complaints', 'Fever', 'Common cold', 'Menstrual pain and heavy bleeding'],
  '2-4g dried herb as tea 3 times daily, or 1-4ml tincture 3 times daily',
  'Safe as mild tea for children over 2',
  ARRAY['tea','tincture','topical','capsule']::public.dosage_form[],
  'For tea, steep 1-2 teaspoons of dried flowering tops for 10-15 minutes. For wound care, apply crushed fresh leaves as a poultice. Yarrow is a bitter herb and makes an excellent digestive tea before meals.',
  ARRAY['Allergy to Asteraceae family', 'Pregnancy', 'Bleeding disorders (contradictory effects)', 'Concurrent blood thinners'],
  ARRAY['Allergic dermatitis', 'Photosensitivity', 'Drowsiness', 'Increased urination'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'anti-inflammatory'),
  true
),
(
  gen_random_uuid(),
  'Eleuthero',
  'eleuthero',
  'Eleutherococcus senticosus',
  ARRAY['Siberian Ginseng', 'Devil''s Shrub', 'Ci Wu Jia', 'Eleuthero Root'],
  'Eleuthero, formerly known as Siberian ginseng, is a thorny shrub native to northeastern Asia. It was extensively studied in Russia as an adaptogen for enhancing performance under stress. Though not a true ginseng (Panax), it shares adaptogenic properties and was used by Russian astronauts and athletes.',
  ARRAY['Eleutherosides', 'Syringin', 'Isofraxidin', 'Polysaccharides', 'Chlorogenic acid'],
  ARRAY['Stamina enhancer', 'Stress resistance', 'Immune booster', 'Adaptogen', 'Longevity tonic'],
  ARRAY['Physical and mental fatigue', 'Stress management', 'Athletic performance', 'Immune support', 'Chronic fatigue syndrome'],
  '300-1200mg dried root extract daily, or 2-4ml tincture 2-3 times daily',
  'Not recommended for children under 12',
  ARRAY['capsule','tincture','tea','tablet','extract']::public.dosage_form[],
  'Take in the morning to avoid sleep interference. Cycle: 6-8 weeks on, 2 weeks off. For tea, simmer 1 teaspoon of dried root for 15-20 minutes. Standardized extracts should contain eleutherosides B and E.',
  ARRAY['Hypertension', 'Autoimmune conditions', 'Hormone-sensitive conditions', 'Concurrent heart medications'],
  ARRAY['Insomnia', 'Irritability', 'Headache', 'Anxiety', 'Diarrhea'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'American Ginseng',
  'american-ginseng',
  'Panax quinquefolius',
  ARRAY['Xi Yang Shen', 'Canadian Ginseng', 'Sang', 'Five-Fingers'],
  'American ginseng is native to North America and has been used by Native Americans for centuries and in Traditional Chinese Medicine as a yin tonic. It is considered more cooling than Asian ginseng and is preferred for those who find Asian ginseng too stimulating. It is particularly well-studied for blood sugar regulation and immune function.',
  ARRAY['Ginsenosides (Rb1 dominant)', 'Polysaccharides', 'Polyacetylenes', 'Peptidoglycans', 'Flavonoids'],
  ARRAY['Cooling tonic', 'Fever treatment', 'Digestive aid', 'Respiratory support', 'Energy without overstimulation'],
  ARRAY['Blood sugar regulation', 'Immune function (cold prevention)', 'Cognitive function', 'Cancer-related fatigue', 'Upper respiratory infection prevention'],
  '200-400mg standardized extract daily, or 1-2g dried root daily',
  'Not recommended for children under 12',
  ARRAY['capsule','tea','tincture','powder','extract']::public.dosage_form[],
  'Considered better for those with heat conditions or who find Asian ginseng too stimulating. For blood sugar, take before meals. Ceragen and CVT-E002 are well-studied standardized extracts. Do not confuse with Asian ginseng.',
  ARRAY['Hormone-sensitive conditions', 'Autoimmune conditions', 'Concurrent diabetes medications', 'Pre-surgery'],
  ARRAY['Headache', 'Insomnia', 'GI upset', 'Nervousness', 'Breast tenderness'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Schisandra',
  'schisandra',
  'Schisandra chinensis',
  ARRAY['Five-Flavor Berry', 'Wu Wei Zi', 'Magnolia Vine', 'Chinese Magnolia Vine'],
  'Schisandra is a vine that produces bright red berries used in Traditional Chinese Medicine for over 2,000 years. It is called "five-flavor berry" because it contains all five tastes recognized in Chinese medicine: sweet, sour, salty, bitter, and pungent. It is classified as a superior adaptogen and liver protectant.',
  ARRAY['Schisandrin', 'Gomisin A', 'Deoxyschisandrin', 'Schisandrol B', 'Lignans'],
  ARRAY['Liver protection', 'Endurance enhancer', 'Mental clarity', 'Longevity tonic', 'Respiratory support'],
  ARRAY['Liver protection and hepatitis support', 'Physical performance', 'Mental focus and memory', 'Stress adaptation', 'Sleep quality'],
  '500-2000mg dried berry or 250-500mg extract daily',
  'Not recommended for children under 12',
  ARRAY['capsule','powder','tincture','tea','extract']::public.dosage_form[],
  'Dried berries can be chewed or made into tea (simmer for 20 minutes). Standardized extracts should contain schisandrin content. Often combined with other adaptogens. In TCM, used as both morning energizer and evening calming agent.',
  ARRAY['Epilepsy', 'GERD (may increase stomach acid)', 'Pregnancy', 'Intracranial pressure conditions'],
  ARRAY['GI upset', 'Heartburn', 'Decreased appetite', 'Skin rash', 'Allergic reactions'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'adaptogen'),
  true
),
(
  gen_random_uuid(),
  'Bacopa',
  'bacopa',
  'Bacopa monnieri',
  ARRAY['Brahmi', 'Water Hyssop', 'Herb of Grace', 'Indian Pennywort'],
  'Bacopa is a creeping herb that thrives in wetlands throughout South and Southeast Asia. It is one of the most important nootropic herbs in Ayurvedic medicine, with a history of over 3,000 years of use for cognitive enhancement. Modern clinical trials support its use for memory, attention, and cognitive processing speed.',
  ARRAY['Bacosides A and B', 'Bacopasides', 'Brahmine', 'Herpestine', 'Apigenin'],
  ARRAY['Memory enhancement', 'Learning aid', 'Anti-anxiety', 'Epilepsy treatment', 'Cognitive tonic'],
  ARRAY['Memory and learning', 'ADHD support', 'Anxiety', 'Cognitive decline prevention', 'Neuroprotection'],
  '300-450mg standardized extract (50% bacosides) daily',
  'Limited pediatric data; some studies used 225mg for ages 6-12',
  ARRAY['capsule','powder','tincture','tea','extract']::public.dosage_form[],
  'Take with a fat-containing meal for better absorption of bacosides. Effects on cognition typically take 8-12 weeks of consistent use. Standardized to at least 50% bacosides. May cause initial GI discomfort that subsides with continued use.',
  ARRAY['Thyroid conditions (may increase thyroid hormones)', 'Concurrent thyroid medications', 'GI conditions', 'Urinary tract obstruction'],
  ARRAY['GI upset', 'Nausea', 'Cramping', 'Bloating', 'Dry mouth', 'Fatigue'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nootropic'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Calendula',
  'calendula',
  'Calendula officinalis',
  ARRAY['Pot Marigold', 'Garden Marigold', 'Gold Bloom', 'Holligold'],
  'Calendula is a bright orange flowering plant that has been used in European herbal medicine for over 800 years, primarily for wound healing and skin conditions. It is one of the safest and most versatile herbs for topical use and has demonstrated anti-inflammatory, antimicrobial, and wound-healing properties in numerous studies.',
  ARRAY['Triterpenoids', 'Faradiol', 'Flavonoids', 'Carotenoids', 'Saponins'],
  ARRAY['Wound healing', 'Skin conditions', 'Eye infections', 'Menstrual regulation', 'Anti-inflammatory'],
  ARRAY['Wound care and burns', 'Eczema and dermatitis', 'Oral health (mouth rinse)', 'Radiation dermatitis', 'Diaper rash'],
  'Topical: apply cream or oil 2-3 times daily; Internal: 1-2 cups tea daily',
  'Topical use safe for all ages including infants; internal tea for ages 2+',
  ARRAY['topical','tea','tincture','extract','other']::public.dosage_form[],
  'For topical use, infuse dried flowers in olive oil for 2-4 weeks or use commercially prepared creams. For tea, steep 1-2 teaspoons of dried flowers for 10 minutes. As a mouth rinse, use cooled tea. Combine with comfrey for enhanced wound healing.',
  ARRAY['Allergy to Asteraceae family', 'Pregnancy (internal use)'],
  ARRAY['Allergic reactions in sensitive individuals', 'Drowsiness (internal)', 'Skin irritation (rare)'],
  false,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'skin-topical'),
  true
),
(
  gen_random_uuid(),
  'Tea Tree',
  'tea-tree',
  'Melaleuca alternifolia',
  ARRAY['Australian Tea Tree', 'Melaleuca', 'Ti Tree', 'Paper Bark Tree'],
  'Tea tree is native to Australia and has been used by Aboriginal Australians for thousands of years as a traditional antiseptic. Its essential oil is one of the most well-researched antimicrobial essential oils, effective against bacteria, fungi, and viruses. It became widely known after its use by Australian soldiers in World War II.',
  ARRAY['Terpinen-4-ol', 'Gamma-terpinene', 'Alpha-terpinene', '1,8-Cineole', 'Alpha-terpineol'],
  ARRAY['Wound antiseptic', 'Skin infections', 'Insect bites', 'Respiratory infections', 'Fungal infections'],
  ARRAY['Acne treatment', 'Fungal nail infections', 'Athlete''s foot', 'Head lice', 'Wound care'],
  'Topical only: 5-10% tea tree oil solution for acne; 100% oil for nail fungus applied with cotton swab',
  'Topical use for children over 6; dilute to 2-5% concentration',
  ARRAY['essential_oil','topical']::public.dosage_form[],
  'TOPICAL USE ONLY. Never ingest tea tree oil (toxic). Dilute in carrier oil for general skin use (5-10% concentration). For acne, 5% tea tree oil gel is as effective as 5% benzoyl peroxide with fewer side effects. Patch test first.',
  ARRAY['Internal use (toxic)', 'Sensitivity to tea tree oil', 'Cats and dogs (toxic to pets)'],
  ARRAY['Contact dermatitis', 'Skin irritation', 'Allergic reactions', 'TOXICITY IF INGESTED', 'Gynecomastia in prepubertal boys (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'antimicrobial'),
  true
),
(
  gen_random_uuid(),
  'Witch Hazel',
  'witch-hazel',
  'Hamamelis virginiana',
  ARRAY['Winter Bloom', 'Snapping Hazel', 'Spotted Alder', 'Tobacco Wood'],
  'Witch hazel is a shrub native to North America whose bark and leaves have been used by Native Americans for centuries for skin conditions and inflammation. It is one of the most widely used botanical ingredients in cosmetics and personal care products, valued for its astringent and anti-inflammatory properties.',
  ARRAY['Hamamelitannin', 'Catechins', 'Gallic acid', 'Proanthocyanidins', 'Volatile oils'],
  ARRAY['Skin astringent', 'Hemorrhoid treatment', 'Wound healing', 'Eye inflammation', 'Insect bite relief'],
  ARRAY['Hemorrhoids', 'Varicose veins', 'Acne and oily skin', 'Minor skin irritation', 'Postpartum perineal care'],
  'Apply topical distillate or extract as needed; 2-3g bark as tea for internal use',
  'Topical use safe for children of all ages',
  ARRAY['topical','extract','tea','tincture']::public.dosage_form[],
  'Witch hazel distillate (available at most pharmacies) can be applied directly to skin with cotton pad. For hemorrhoids, soak pads in witch hazel and apply. Internal use is limited; the astringent properties are most valuable topically.',
  ARRAY['Internal use in large amounts', 'Open wounds (distillate with alcohol)'],
  ARRAY['Skin irritation (rare)', 'Stomach upset (internal use)', 'Nausea (internal use)'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'skin-topical'),
  true
),
(
  gen_random_uuid(),
  'Horse Chestnut',
  'horse-chestnut',
  'Aesculus hippocastanum',
  ARRAY['Conker Tree', 'Buckeye', 'Spanish Chestnut'],
  'Horse chestnut is a large tree native to southeastern Europe whose seed extract is one of the best-studied herbal remedies for chronic venous insufficiency. Its primary compound, aescin, has demonstrated anti-inflammatory and venotonic properties. Raw horse chestnuts are toxic; only standardized, processed extracts should be used.',
  ARRAY['Aescin (escin)', 'Proanthocyanidins', 'Coumarins', 'Flavonoids', 'Kaempferol'],
  ARRAY['Vein health', 'Hemorrhoid treatment', 'Swelling reduction', 'Circulatory support', 'Anti-inflammatory'],
  ARRAY['Chronic venous insufficiency', 'Varicose veins', 'Hemorrhoids', 'Leg edema', 'Post-surgical edema'],
  '300mg standardized extract (50mg aescin) twice daily',
  'Not recommended for children under 18',
  ARRAY['capsule','tablet','topical','extract']::public.dosage_form[],
  'Only use commercially prepared, standardized extracts (raw seeds are toxic). Standardized to 16-20% aescin (also spelled escin). Take with meals. Topical creams containing aescin can be applied to affected areas. Effects may take 2-4 weeks.',
  ARRAY['Bleeding disorders', 'Kidney disease', 'Liver disease', 'Concurrent blood thinners', 'Raw seed consumption (toxic)'],
  ARRAY['GI upset', 'Nausea', 'Itching', 'Headache', 'Dizziness', 'TOXICITY IF RAW SEEDS CONSUMED'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'cardiovascular'),
  true
),
(
  gen_random_uuid(),
  'Gymnema',
  'gymnema',
  'Gymnema sylvestre',
  ARRAY['Gurmar', 'Sugar Destroyer', 'Australian Cowplant', 'Miracle Fruit'],
  'Gymnema is a woody climbing vine native to India and Africa, known in Ayurveda as "gurmar" meaning "sugar destroyer." When chewed, its leaves temporarily block the ability to taste sweetness. It has been used for over 2,000 years for diabetes management and modern research confirms its blood sugar-lowering effects.',
  ARRAY['Gymnemic acids', 'Gymnemasaponins', 'Gurmarin', 'Stigmasterol', 'Betaine'],
  ARRAY['Diabetes treatment', 'Sugar craving reducer', 'Weight management', 'Digestive aid', 'Anti-inflammatory'],
  ARRAY['Type 2 diabetes support', 'Sugar craving reduction', 'Metabolic syndrome', 'Weight management', 'Pancreatic beta cell regeneration support'],
  '200-400mg standardized extract (25% gymnemic acids) 2 times daily before meals',
  'Not recommended for children without medical supervision',
  ARRAY['capsule','tablet','tea','extract','powder']::public.dosage_form[],
  'Take before meals for blood sugar support. Chewing fresh leaves blocks sweet taste for 1-2 hours, which can help reduce sugar cravings. Standardized to 25-75% gymnemic acids. May take 18-24 months for full pancreatic benefit in traditional use.',
  ARRAY['Concurrent diabetes medications (risk of hypoglycemia)', 'Concurrent insulin', 'Scheduled surgery'],
  ARRAY['Hypoglycemia (with diabetes medications)', 'GI upset', 'Headache', 'Nausea', 'Altered taste'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'metabolic'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Meadowsweet',
  'meadowsweet',
  'Filipendula ulmaria',
  ARRAY['Queen of the Meadow', 'Bridewort', 'Meadow Queen', 'Spiraea'],
  'Meadowsweet is a flowering plant native to Europe and Western Asia that was historically so valued it was one of the three most sacred herbs of the Druids. It contains salicylates (the basis for aspirin, which was named after its old botanical name Spiraea) but is considered gentler on the stomach than aspirin.',
  ARRAY['Salicylaldehyde', 'Methyl salicylate', 'Salicin', 'Rutin', 'Tannins'],
  ARRAY['Fever reducer', 'Pain relief', 'Digestive aid', 'Anti-rheumatic', 'Heartburn remedy'],
  ARRAY['Digestive complaints and heartburn', 'Fever', 'Joint pain', 'Headaches', 'Ulcer support (gastroprotective)'],
  '2-6g dried herb as tea 3 times daily, or 2-4ml tincture 3 times daily',
  'Safe as tea for children over 2 at reduced doses',
  ARRAY['tea','tincture','capsule']::public.dosage_form[],
  'For tea, steep dried flowering tops and leaves in hot water for 10-15 minutes. Unlike pure aspirin, meadowsweet is gastroprotective due to its tannin and mucilage content. Makes an excellent digestive tea.',
  ARRAY['Aspirin allergy or sensitivity', 'Children under 16 with viral illness (Reye syndrome)', 'Bleeding disorders'],
  ARRAY['GI upset (rare)', 'Nausea', 'Allergic reactions in aspirin-sensitive individuals'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'digestive'),
  true
),
(
  gen_random_uuid(),
  'Plantain',
  'plantain',
  'Plantago major',
  ARRAY['Broadleaf Plantain', 'Greater Plantain', 'Ribwort', 'Waybread'],
  'Plantain (not the banana relative) is a ubiquitous "weed" found on every continent, used medicinally across virtually all traditional medicine systems. It is one of the most accessible healing plants, valued for its wound-healing, anti-inflammatory, and respiratory properties. Shakespeare and Anglo-Saxon herbalists documented its medicinal virtues.',
  ARRAY['Aucubin', 'Allantoin', 'Mucilage', 'Tannins', 'Baicalein'],
  ARRAY['Wound healing', 'Insect bite treatment', 'Cough remedy', 'Digestive aid', 'Blood purifier'],
  ARRAY['Wound care and insect bites', 'Cough and bronchitis', 'Urinary tract infections', 'Skin inflammation', 'Oral health'],
  '3-5g dried leaf as tea 3 times daily, or fresh leaf poultice as needed',
  'Safe as tea for children over 1; poultice safe for all ages',
  ARRAY['tea','tincture','topical','capsule']::public.dosage_form[],
  'For insect bites and stings, chew a fresh leaf and apply as a poultice for immediate relief. For tea, steep dried leaves for 10-15 minutes. Psyllium (Plantago ovata) is a related species used for fiber supplementation.',
  ARRAY['Allergy to Plantaginaceae family'],
  ARRAY['Allergic reactions (rare)', 'GI upset at high doses'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'skin-topical'),
  true
),
(
  gen_random_uuid(),
  'Milk Vetch',
  'milk-vetch',
  'Astragalus propinquus',
  ARRAY['Bei Qi', 'Huang Qi variant', 'Chinese Milk Vetch'],
  'This species is closely related to the primary Astragalus (A. membranaceus) and is sometimes used interchangeably in Chinese medicine. It is included in many patent Chinese herbal formulas for immune support. Like its close relative, it is valued for Qi tonification and immune-modulating properties.',
  ARRAY['Astragalosides', 'Polysaccharides', 'Flavonoids', 'Isoflavonoids', 'Saponins'],
  ARRAY['Immune tonic', 'Qi tonification', 'Spleen support', 'Lung tonic', 'Edema treatment'],
  ARRAY['Immune system support', 'Chronic fatigue', 'Recurrent infections', 'Adjunct cancer support', 'Kidney protection'],
  '250-500mg extract 2-3 times daily, or 9-30g dried root in decoction',
  'Generally safe for children over 6 at reduced doses',
  ARRAY['capsule','tea','tincture','powder','extract']::public.dosage_form[],
  'Often used interchangeably with A. membranaceus. Simmer root slices in soups and broths as traditional TCM food therapy. Used preventatively, not during acute illness.',
  ARRAY['Autoimmune conditions', 'Immunosuppressant medications', 'Active infections (some practitioners avoid)'],
  ARRAY['GI upset', 'Mild diarrhea', 'Allergic reactions (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'immune-support'),
  true
),
(
  gen_random_uuid(),
  'White Willow',
  'white-willow',
  'Salix alba',
  ARRAY['Willow Bark', 'European Willow', 'Salicin Bark'],
  'White willow bark is the original source of salicylic acid from which aspirin was derived. It has been used for pain and fever since the time of Hippocrates. The bark contains a complex of salicylates that work synergistically, providing a gentler and more sustained effect than isolated aspirin.',
  ARRAY['Salicin', 'Salicortin', 'Populin', 'Tannins', 'Flavonoids'],
  ARRAY['Pain relief', 'Fever reduction', 'Anti-inflammatory', 'Headache treatment', 'Gout remedy'],
  ARRAY['Chronic low back pain', 'Osteoarthritis', 'Headaches', 'Inflammatory conditions', 'Fever reduction'],
  '120-240mg salicin daily from standardized extract',
  'Not recommended for children under 16',
  ARRAY['capsule','tea','tincture','extract','tablet']::public.dosage_form[],
  'Look for extracts standardized to salicin content. Decoct bark in water for 15-20 minutes for tea. Onset of action is slower than aspirin but duration is longer. Safer on the stomach than aspirin due to other bark constituents.',
  ARRAY['Aspirin allergy', 'Bleeding disorders', 'Children under 16', 'Kidney disease', 'Concurrent blood thinners'],
  ARRAY['GI upset', 'Nausea', 'Allergic reactions', 'Kidney irritation (high doses)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'analgesic'),
  true
),
(
  gen_random_uuid(),
  'Uva Ursi',
  'uva-ursi',
  'Arctostaphylos uva-ursi',
  ARRAY['Bearberry', 'Kinnikinnick', 'Bear''s Grape', 'Hogberry'],
  'Uva ursi is an evergreen shrub found in northern latitudes, long used by Native Americans and European herbalists for urinary tract conditions. Its primary active compound, arbutin, is converted to hydroquinone in alkaline urine, providing antiseptic action specifically in the urinary tract.',
  ARRAY['Arbutin', 'Methylarbutin', 'Ursolic acid', 'Tannins', 'Gallic acid'],
  ARRAY['Urinary tract antiseptic', 'Kidney stone remedy', 'Diuretic', 'Astringent', 'Wound healing'],
  ARRAY['Urinary tract infections', 'Cystitis', 'Urethritis', 'Mild kidney inflammation'],
  '400-800mg standardized extract (20% arbutin) 3 times daily for up to 1 week',
  'Not recommended for children under 12',
  ARRAY['capsule','tea','tincture','tablet']::public.dosage_form[],
  'For maximum efficacy, urine should be alkaline (eat alkaline foods, avoid acidic foods during treatment). Soak leaves in cold water for several hours for tea to minimize tannin extraction. Limit use to 1 week at a time, maximum 5 times per year.',
  ARRAY['Kidney disease', 'Pregnancy', 'Children under 12', 'Liver disease', 'Long-term use (hydroquinone toxicity)'],
  ARRAY['Nausea', 'Green-brown urine discoloration', 'GI upset', 'Liver toxicity (chronic use)', 'Allergic reactions'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'urinary'),
  true
),
(
  gen_random_uuid(),
  'Andrographis',
  'andrographis',
  'Andrographis paniculata',
  ARRAY['King of Bitters', 'Kalmegh', 'Green Chiretta', 'Chuan Xin Lian'],
  'Andrographis is an annual plant native to South Asia, known as the "King of Bitters" for its intensely bitter taste. It is used extensively in Ayurvedic and Traditional Chinese Medicine for infections and fevers. Clinical trials support its effectiveness for reducing duration and severity of upper respiratory infections.',
  ARRAY['Andrographolide', 'Neoandrographolide', 'Deoxyandrographolide', 'Andrograpanin', 'Flavonoids'],
  ARRAY['Fever treatment', 'Cold and flu remedy', 'Liver protection', 'Digestive aid', 'Anti-inflammatory'],
  ARRAY['Upper respiratory infections', 'Common cold treatment', 'Inflammatory conditions', 'Liver protection', 'Immune stimulation'],
  '200mg standardized extract (30% andrographolide) 2-3 times daily during illness',
  'Not recommended for children under 12 without supervision',
  ARRAY['capsule','tablet','tincture','extract']::public.dosage_form[],
  'Most effective when started within 72 hours of cold symptom onset. Use standardized extract containing 30% andrographolides. Extremely bitter; capsules or tablets are preferred over tea. Typically used for acute conditions (1-2 weeks), not long-term.',
  ARRAY['Autoimmune conditions', 'Bleeding disorders', 'Pregnancy (strong anti-fertility effects)', 'Concurrent immunosuppressants'],
  ARRAY['GI upset', 'Fatigue', 'Headache', 'Allergic reactions', 'Loss of appetite', 'Diarrhea'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'immune-support'),
  true
),
(
  gen_random_uuid(),
  'Coleus',
  'coleus',
  'Coleus forskohlii',
  ARRAY['Forskolin', 'Makandi', 'Indian Coleus', 'Plectranthus barbatus'],
  'Coleus forskohlii is a tropical plant in the mint family, native to India, Nepal, and Thailand. It has been used in Ayurvedic medicine for centuries for heart and lung conditions. Its primary compound, forskolin, directly activates adenylate cyclase, an enzyme fundamental to many cellular processes.',
  ARRAY['Forskolin', 'Rosmarinic acid', 'Flavonoids', 'Diterpenoids', 'Beta-sitosterol'],
  ARRAY['Heart tonic', 'Respiratory support', 'Digestive aid', 'Eye pressure treatment', 'Weight management'],
  ARRAY['Glaucoma (eye drops)', 'Asthma', 'Weight management', 'Hypothyroidism support', 'Cardiovascular health'],
  '250mg standardized extract (10% forskolin) 2 times daily',
  'Not recommended for children',
  ARRAY['capsule','extract','tablet']::public.dosage_form[],
  'Standardized to 10-20% forskolin. Take with meals. For glaucoma, specific ophthalmic preparations are used (not oral supplements). May lower blood pressure; monitor if already on BP medications.',
  ARRAY['Low blood pressure', 'Concurrent blood pressure medications', 'Bleeding disorders', 'Pre-surgery', 'Peptic ulcers'],
  ARRAY['Low blood pressure', 'Increased heart rate', 'GI upset', 'Headache', 'Flushing'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'metabolic'),
  true
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'Clove',
  'clove',
  'Syzygium aromaticum',
  ARRAY['Clove Bud', 'Lavang', 'Ding Xiang', 'Eugenia'],
  'Clove is an aromatic flower bud native to Indonesia, used in medicine and cooking for over 2,000 years. Its primary compound, eugenol, has potent analgesic and antimicrobial properties. Clove oil is one of the most traditional and effective remedies for toothache and dental pain.',
  ARRAY['Eugenol', 'Eugenyl acetate', 'Beta-caryophyllene', 'Gallic acid', 'Kaempferol'],
  ARRAY['Toothache remedy', 'Digestive aid', 'Antimicrobial', 'Pain relief', 'Breath freshener'],
  ARRAY['Dental pain', 'Oral infections', 'Digestive support', 'Antimicrobial applications', 'Anti-inflammatory'],
  'Clove oil: 1-2 drops applied topically for dental pain; Internal: 1-2 cloves or 100-250mg daily',
  'Culinary amounts safe; clove oil topically for ages 2+ (diluted)',
  ARRAY['essential_oil','powder','capsule','tea','topical']::public.dosage_form[],
  'For toothache, apply a small amount of clove oil on a cotton ball directly to the affected tooth. Dilute oil for skin application. For tea, simmer 2-3 whole cloves in water for 10 minutes. Do not apply undiluted clove oil to gums repeatedly.',
  ARRAY['Bleeding disorders', 'Pre-surgery', 'Liver disease', 'Undiluted use on mucous membranes'],
  ARRAY['Gum irritation', 'Mouth tissue damage (undiluted oil)', 'GI upset', 'Allergic reactions', 'Blood thinning'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'antimicrobial'),
  true
),
(
  gen_random_uuid(),
  'Artichoke',
  'artichoke',
  'Cynara cardunculus var. scolymus',
  ARRAY['Globe Artichoke', 'Artichoke Leaf', 'Cynara'],
  'Artichoke leaf extract is a well-studied herbal remedy for digestive and liver complaints in European phytomedicine. The leaves (not the edible flower bud) contain cynarin and chlorogenic acid, which stimulate bile production and support liver detoxification. It is approved by the German Commission E for dyspeptic complaints.',
  ARRAY['Cynarin', 'Chlorogenic acid', 'Luteolin', 'Cynaropicrin', 'Inulin'],
  ARRAY['Liver tonic', 'Digestive aid', 'Bile stimulant', 'Cholesterol reducer', 'Appetite stimulant'],
  ARRAY['Dyspepsia and IBS', 'Cholesterol reduction', 'Liver protection', 'Bile flow support', 'Blood sugar regulation'],
  '320-640mg standardized leaf extract 3 times daily',
  'Not well studied in children; likely safe for ages 12+ at reduced doses',
  ARRAY['capsule','tablet','tincture','tea','extract']::public.dosage_form[],
  'Take before meals for digestive support. Standardized to cynarin or caffeoylquinic acids. For tea, steep dried leaves for 10-15 minutes (quite bitter). Most effective when taken consistently for 4-6 weeks.',
  ARRAY['Bile duct obstruction', 'Gallstones', 'Allergy to Asteraceae family'],
  ARRAY['Gas', 'GI upset', 'Allergic reactions', 'Increased hunger'],
  true,
  true,
  (SELECT id FROM public.herb_categories WHERE slug = 'liver-support'),
  true
),
(
  gen_random_uuid(),
  'Black Walnut',
  'black-walnut',
  'Juglans nigra',
  ARRAY['American Walnut', 'Eastern Black Walnut'],
  'Black walnut hull has been used in traditional herbal medicine primarily for its antiparasitic and antifungal properties. The green outer hulls of the unripe fruit contain juglone, a naphthoquinone with broad antimicrobial activity. It is a key component of many traditional parasite cleanse protocols.',
  ARRAY['Juglone', 'Tannins', 'Ellagic acid', 'Quercetin', 'Plumbagin'],
  ARRAY['Antiparasitic', 'Antifungal', 'Astringent', 'Laxative', 'Skin conditions'],
  ARRAY['Intestinal parasites', 'Fungal infections', 'Ringworm and athlete''s foot', 'Candida overgrowth', 'Acne'],
  '250-500mg hull extract daily for up to 2 weeks, or topically as needed',
  'Not recommended for children without medical supervision',
  ARRAY['capsule','tincture','topical','extract']::public.dosage_form[],
  'Green hull tincture is the traditional preparation for parasites. For topical antifungal use, apply diluted hull extract. Use for short periods only (2 weeks max for internal use). Often combined with clove and wormwood in parasite protocols.',
  ARRAY['Nut allergy', 'Liver disease', 'Kidney disease', 'Pregnancy', 'Long-term internal use'],
  ARRAY['GI upset', 'Staining of skin and mucous membranes', 'Nausea', 'Liver toxicity (chronic use)', 'Kidney irritation'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'antimicrobial'),
  true
),
(
  gen_random_uuid(),
  'Tongkat Ali',
  'tongkat-ali',
  'Eurycoma longifolia',
  ARRAY['Longjack', 'Malaysian Ginseng', 'Pasak Bumi', 'Ali''s Walking Stick'],
  'Tongkat ali is a flowering plant native to Southeast Asia, traditionally used as a male tonic and energy enhancer. Clinical research supports its use for male hormonal health, stress management, and physical performance. It has become one of the most popular herbal supplements for testosterone support.',
  ARRAY['Eurycomanone', 'Quassinoids', 'Eurycomalactone', 'Squalene derivatives', 'Alkaloids'],
  ARRAY['Male vitality', 'Energy enhancer', 'Fever treatment', 'Antimalarial', 'Aphrodisiac'],
  ARRAY['Testosterone support', 'Male fertility', 'Physical performance', 'Stress and cortisol management', 'Body composition improvement'],
  '200-400mg standardized extract (2% eurycomanone) daily',
  'Not indicated for children',
  ARRAY['capsule','powder','extract','tablet']::public.dosage_form[],
  'Use standardized, tested extracts (risk of contamination and adulteration is high). Take with food. Cycling (5 days on, 2 off) is commonly recommended. Look for products tested for heavy metals. Effects may take 2-4 weeks.',
  ARRAY['Hormone-sensitive cancers', 'Heart conditions', 'Kidney/liver disease', 'Diabetes', 'Immune conditions'],
  ARRAY['Insomnia', 'Restlessness', 'Anxiety', 'GI upset', 'Increased body temperature'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'mens-health'),
  true
),
(
  gen_random_uuid(),
  'Wormwood',
  'wormwood',
  'Artemisia absinthium',
  ARRAY['Absinthium', 'Grand Wormwood', 'Absinthe', 'Mugwort Wormwood'],
  'Wormwood is a perennial herb known historically as the key ingredient in absinthe. It has been used medicinally since ancient Egypt for digestive complaints and parasitic infections. Its compound artemisinin (from related species A. annua) won the Nobel Prize in 2015 for treating malaria.',
  ARRAY['Absinthin', 'Artabsin', 'Thujone', 'Chamazulene', 'Bisabolol'],
  ARRAY['Digestive bitter', 'Antiparasitic', 'Fever treatment', 'Appetite stimulant', 'Menstrual regulator'],
  ARRAY['Digestive complaints', 'Loss of appetite', 'Parasitic infections', 'Small intestinal bacterial overgrowth (SIBO)', 'Crohn''s disease support'],
  '1-1.5g dried herb as tea 3 times daily for up to 4 weeks, or 200-300mg extract daily',
  'Not recommended for children under 18',
  ARRAY['tea','tincture','capsule','extract']::public.dosage_form[],
  'IMPORTANT: Contains thujone which is neurotoxic in large doses. Use only for short periods (2-4 weeks maximum). For tea, steep (do not boil) 1 teaspoon dried herb for 5-10 minutes. Extremely bitter; often combined with other digestive herbs. Not the same as sweet wormwood (A. annua).',
  ARRAY['Pregnancy (abortifacient)', 'Seizure disorders (thujone)', 'Kidney disease', 'Liver disease', 'Long-term use'],
  ARRAY['Nausea', 'Vomiting', 'Dizziness', 'Seizures (thujone toxicity at high doses)', 'Restlessness', 'Hallucinations (excessive use)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'digestive'),
  true
),
(
  gen_random_uuid(),
  'Elderberry Syrup',
  'sambucol',
  'Sambucus nigra (standardized)',
  ARRAY['Sambucol', 'Elderberry Extract', 'Black Elder Syrup'],
  'Standardized elderberry syrup preparations have become one of the most popular natural cold and flu remedies. Products like Sambucol have been specifically studied in clinical trials and shown to reduce cold and flu duration. This entry represents the standardized extract form distinct from raw elderberry preparations.',
  ARRAY['Anthocyanins (standardized)', 'Flavonoids', 'Vitamin C', 'Polyphenols'],
  ARRAY['Flu treatment', 'Cold prevention', 'Immune support'],
  ARRAY['Influenza treatment and duration reduction', 'Common cold management', 'Daily immune support', 'Traveler''s immune protection'],
  '15ml (1 tablespoon) standardized syrup 4 times daily during illness; 15ml daily for prevention',
  '5-10ml daily for children 2-12; 15ml for ages 12+',
  ARRAY['other','capsule','extract']::public.dosage_form[],
  'Standardized syrups provide consistent anthocyanin content. Start at first sign of symptoms for best results. Can be taken daily during cold and flu season for prevention. Gummy and lozenge forms are also available.',
  ARRAY['Autoimmune conditions', 'Immunosuppressant medications'],
  ARRAY['GI upset', 'Nausea'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'immune-support'),
  true
),
(
  gen_random_uuid(),
  'Stinging Nettle Root',
  'nettle-root',
  'Urtica dioica (root)',
  ARRAY['Nettle Root', 'Urtica Root', 'Brennesselwurzel'],
  'Stinging nettle root is a distinct medicinal preparation from nettle leaf, with different active compounds and therapeutic applications. While the leaf is used primarily for allergies and nutrition, the root is specifically studied for prostate health and urinary symptoms. It is approved by the German Commission E for BPH.',
  ARRAY['Lignans', 'Beta-sitosterol', 'Scopoletin', 'Lectins (UDA)', 'Polysaccharides'],
  ARRAY['Prostate health', 'Urinary support', 'Hair loss prevention', 'Hormonal regulation', 'Diuretic'],
  ARRAY['Benign prostatic hyperplasia (BPH)', 'Lower urinary tract symptoms', 'Hormonal balance', 'Hair loss support', 'Urinary flow improvement'],
  '300-600mg standardized root extract daily',
  'Not indicated for children',
  ARRAY['capsule','tincture','tea','extract','tablet']::public.dosage_form[],
  'Specifically use root preparations (not leaf) for prostate conditions. Often combined with saw palmetto and pygeum for enhanced prostate support. For tea, simmer root in water for 15-20 minutes. Effects may take 4-6 weeks.',
  ARRAY['Fluid retention from heart or kidney failure', 'Concurrent BPH medications (monitor closely)'],
  ARRAY['GI upset', 'Sweating', 'Allergic reactions (rare)'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'mens-health'),
  true
)
ON CONFLICT (slug) DO NOTHING;


INSERT INTO public.herbs (
  id, name, slug, scientific_name, common_names, description,
  active_compounds, traditional_uses, modern_uses,
  dosage_adult, dosage_child, dosage_forms, preparation_notes,
  contraindications, side_effects, pregnancy_safe, nursing_safe,
  category_id, is_published
) VALUES
(
  gen_random_uuid(),
  'St. John''s Wort',
  'st-johns-wort',
  'Hypericum perforatum',
  ARRAY['Goatweed', 'Klamath Weed', 'Tipton''s Weed', 'Rosin Rose'],
  'St. John''s Wort is a flowering plant that has been used medicinally since ancient Greece. It is best known for its use in treating mild to moderate depression, where clinical evidence supports its efficacy comparable to some conventional antidepressants. It is named for its traditional harvest on St. John''s Day.',
  ARRAY['Hypericin', 'Hyperforin', 'Adhyperforin', 'Flavonoids', 'Xanthones'],
  ARRAY['Depression treatment', 'Wound healing', 'Nerve pain relief', 'Anti-inflammatory', 'Sedative'],
  ARRAY['Mild to moderate depression', 'Seasonal affective disorder', 'Anxiety', 'Nerve pain', 'Menopausal symptoms'],
  '300mg extract (0.3% hypericin) 3 times daily',
  'Not recommended for children under 12',
  ARRAY['capsule','tablet','tincture','tea','extract']::public.dosage_form[],
  'Effects may take 4-6 weeks to become apparent. Standardized extracts should contain 0.3% hypericin or 2-5% hyperforin. Avoid sun exposure as it can cause photosensitivity.',
  ARRAY['Concurrent use with SSRIs or MAOIs', 'Bipolar disorder', 'Schizophrenia', 'Organ transplant recipients', 'HIV patients on antiretrovirals'],
  ARRAY['Photosensitivity', 'Dry mouth', 'Dizziness', 'GI upset', 'Fatigue', 'Restlessness'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'nervine'),
  true
),
(
  gen_random_uuid(),
  'Devil''s Claw',
  'devils-claw',
  'Harpagophytum procumbens',
  ARRAY['Grapple Plant', 'Wood Spider', 'Sengaparile'],
  'Devil''s claw is native to southern Africa and has been used by indigenous San and Khoi peoples for centuries for pain and digestive complaints. It gained popularity in Europe in the 1950s and is now one of the most commonly used herbal analgesics. Its name refers to the fruit''s hooked thorns.',
  ARRAY['Harpagoside', 'Harpagide', 'Procumbide', 'Beta-sitosterol', 'Caffeic acid'],
  ARRAY['Pain relief', 'Fever reduction', 'Digestive aid', 'Anti-inflammatory', 'Blood purifier'],
  ARRAY['Osteoarthritis', 'Low back pain', 'Rheumatic pain', 'Loss of appetite', 'Digestive complaints'],
  '600-1200mg extract (containing 50-100mg harpagoside) daily',
  'Not recommended for children under 18',
  ARRAY['capsule','tablet','tea','tincture','extract']::public.dosage_form[],
  'Standardized extracts should contain at least 1.2% harpagoside. Take with food. Effects on pain may take 4-8 weeks of consistent use. For digestive use, take as bitter tea before meals.',
  ARRAY['Peptic ulcers', 'Gallstones', 'Heart conditions', 'Pregnancy', 'Concurrent blood thinners'],
  ARRAY['GI upset', 'Diarrhea', 'Headache', 'Tinnitus', 'Loss of appetite', 'Allergic reactions'],
  false,
  false,
  (SELECT id FROM public.herb_categories WHERE slug = 'analgesic'),
  true
)
ON CONFLICT (slug) DO NOTHING;
