-- Add FAQ pairs table for Featured Snippet optimization
-- Each herb gets 4-6 high-quality Q&A pairs generated by AI

CREATE TABLE IF NOT EXISTS public.herb_faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  herb_id UUID NOT NULL REFERENCES public.herbs(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general', -- general, safety, dosage, interactions, mechanism
  source TEXT, -- e.g., "ai-generated", "manual", "extracted-from-monograph"
  confidence_score NUMERIC(3,2), -- 0.00 to 1.00, AI confidence
  is_featured BOOLEAN DEFAULT false, -- prioritized for Featured Snippets
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(herb_id, question)
);

CREATE INDEX IF NOT EXISTS idx_herb_faqs_herb_id ON public.herb_faqs (herb_id);
CREATE INDEX IF NOT EXISTS idx_herb_faqs_category ON public.herb_faqs (category);
CREATE INDEX IF NOT EXISTS idx_herb_faqs_featured ON public.herb_faqs (herb_id, is_featured) WHERE is_featured = true;

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_herb_faqs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS herb_faqs_updated_at ON public.herb_faqs;
CREATE TRIGGER herb_faqs_updated_at
  BEFORE UPDATE ON public.herb_faqs
  FOR EACH ROW EXECUTE FUNCTION update_herb_faqs_updated_at();

-- Allow public read access (FAQs are part of the public content)
ALTER TABLE public.herb_faqs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view herb FAQs"
  ON public.herb_faqs FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage herb FAQs"
  ON public.herb_faqs FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
